apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.iamPump.name }}
  name: {{ .Values.iamPump.name }}
spec:
  {{- if not .Values.autoscaling.enabled }} # 防止与HPA自动扩容冲突
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ .Values.iamPump.name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.iamPump.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.iamPump.name }}
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ .Values.iamPump.name }}
        command:
        - /app/iam-pump
        # command: ["sleep"]
        # args: ["infinity"]
        envFrom:
        - secretRef:
            name: {{ .Values.iamPump.secretName }}
        image: "{{ .Values.iamPump.image.repository }}:{{ .Values.iamPump.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.iamPump.image.pullPolicy }}
        {{- with .Values.iamPump.containerPorts }}
        ports:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.iamPump.healthz.port }}
            scheme: HTTP
          {{- toYaml .Values.iamPump.livenessProbe | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.iamPump.healthz.port }}
            scheme: HTTP
          {{- toYaml .Values.iamPump.readinessProbe | nindent 10 }}
        startupProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.iamPump.healthz.port }}
            scheme: HTTP
          {{- toYaml .Values.iamPump.startupProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.iamPump.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /etc/iam/{{ .Values.iamPump.configFileName }}.yaml
          name: config-volume
          readOnly: true
          subPath: {{ .Values.iamPump.configFileName }}.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: {{ .Values.iamPump.configFileName }}.yaml
            path: {{ .Values.iamPump.configFileName }}.yaml
          name: {{ .Values.iamPump.configMapName }}
        name: config-volume
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
