/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

import (
	"github.com/gin-gonic/gin"
)

type AuthAPI struct {
}

// Post /api/v1/auth/login
// 用户登录 
func (api *AuthAPI) ApiV1AuthLoginPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/auth/logout
// 用户退出登录 
func (api *AuthAPI) ApiV1AuthLogoutPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/v1/auth/me
// 获取用户信息 
func (api *AuthAPI) ApiV1AuthMeGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/auth/password/change
// 修改密码 
func (api *AuthAPI) ApiV1AuthPasswordChangePost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/auth/refresh
// 刷新 Token 
func (api *AuthAPI) ApiV1AuthRefreshPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/auth/register
// 用户注册 
func (api *AuthAPI) ApiV1AuthRegisterPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

