/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

import (
	"github.com/gin-gonic/gin"
)

type UserAPI struct {
}

// Get /api/v1/users
// 获取用户列表 
func (api *UserAPI) ApiV1UsersGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /api/v1/users/:id
// 删除用户 
func (api *UserAPI) ApiV1UsersIdDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/v1/users/:id
// 获取指定用户信息 
func (api *UserAPI) ApiV1UsersIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/v1/users/:id
// 更新用户字段 
func (api *UserAPI) ApiV1UsersIdPut(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/users
// 创建用户 
func (api *UserAPI) ApiV1UsersPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

