/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

import (
	"github.com/gin-gonic/gin"
)

type BindingAPI struct {
}

// Get /api/v1/bindings
// 获取 Binding 列表 
func (api *BindingAPI) ApiV1BindingsGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /api/v1/bindings/:id
// 删除 Binding 
func (api *BindingAPI) ApiV1BindingsIdDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/v1/bindings/:id
// 获取指定 Binding 信息 
func (api *BindingAPI) ApiV1BindingsIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/bindings
// 创建 Binding 
func (api *BindingAPI) ApiV1BindingsPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

