/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

// LogoutResponse - 登出响应
type LogoutResponse struct {

	// 是否成功
	Success bool `json:"success,omitempty"`

	// 消息
	Message string `json:"message,omitempty"`
}
