/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

type CreatePolicyRequest struct {

	Name string `json:"name"`

	Description *string `json:"description,omitempty"`

	// 策略内容（JSON格式）
	Content string `json:"content,omitempty"`

	ExtendShadow *map[string]interface{} `json:"extend_shadow,omitempty"`
}
