/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

type CreateSecretRequest struct {

	Description *string `json:"description,omitempty"`

	Expires *int64 `json:"expires,omitempty"`

	ExtendShadow *map[string]interface{} `json:"extend_shadow,omitempty"`
}
