/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

// RegisterResponse - 注册成功响应
type RegisterResponse struct {

	// 用户ID
	UserId int64 `json:"user_id,omitempty"`

	// 用户名
	Username string `json:"username,omitempty"`
}
