/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

type CreateBindingRequest struct {

	SecretId int64 `json:"secret_id"`

	PolicyId int64 `json:"policy_id"`

	ExtendShadow *map[string]interface{} `json:"extend_shadow,omitempty"`
}
