/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

type CreateUserRequest struct {

	// 用户名，全小写字母、数字、下划线，3-32字符
	Username string `json:"username" validate:"regexp=^[a-z0-9_]{3,32}$"`

	// 显示名称
	Nickname string `json:"nickname,omitempty"`

	// 密码，8-64字符
	Password string `json:"password"`

	// 手机号，E.164格式
	Phone *string `json:"phone,omitempty" validate:"regexp=^\\\\+?[1-9]\\\\d{1,14}$"`

	// 邮箱地址
	Email *string `json:"email,omitempty"`

	IsEnable IsEnable `json:"is_enable,omitempty"`

	IsAdmin IsAdmin `json:"is_admin,omitempty"`
}
