/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

import (
	"time"
)

type RotateSecretResponse struct {

	Id int64 `json:"id,omitempty"`

	AccessKey string `json:"access_key,omitempty"`

	SecretKey string `json:"secret_key,omitempty"`

	Expires *int64 `json:"expires,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
