/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

import (
	"time"
)

type BindingResponse struct {

	BindingId int64 `json:"binding_id,omitempty"`

	SecretId int64 `json:"secret_id,omitempty"`

	PolicyId int64 `json:"policy_id,omitempty"`

	Username string `json:"username,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`
}
