/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

type ErrorResponse struct {

	Error string `json:"error,omitempty"`

	ErrorDescription string `json:"error_description,omitempty"`
}
