/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

import (
	"time"
)

type SecretResponse struct {

	Id int64 `json:"id,omitempty"`

	InstanceId string `json:"instance_id,omitempty"`

	UserId int64 `json:"user_id,omitempty"`

	Username string `json:"username,omitempty"`

	AccessKey string `json:"access_key,omitempty"`

	Description *string `json:"description,omitempty"`

	Expires *int64 `json:"expires,omitempty"`

	ExtendShadow *string `json:"extend_shadow,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
