/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

type UpdateUserRequest struct {

	// 显示名称
	Nickname string `json:"nickname,omitempty"`

	// 手机号，E.164格式
	Phone *string `json:"phone,omitempty" validate:"regexp=^\\\\+?[1-9]\\\\d{1,14}$"`

	// 邮箱地址
	Email *string `json:"email,omitempty"`

	IsEnable IsEnable `json:"is_enable,omitempty"`

	IsAdmin IsAdmin `json:"is_admin,omitempty"`

	// 新密码（留空表示不修改）
	Password *string `json:"password,omitempty"`

	// 扩展字段，JSON对象格式
	ExtendShadow *map[string]interface{} `json:"extend_shadow,omitempty"`
}
