/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the AuditAPI part of the API
	AuditAPI AuditAPI
	// Routes for the AuthAPI part of the API
	AuthAPI AuthAPI
	// Routes for the BindingAPI part of the API
	BindingAPI BindingAPI
	// Routes for the PolicyAPI part of the API
	PolicyAPI PolicyAPI
	// Routes for the SecretAPI part of the API
	SecretAPI SecretAPI
	// Routes for the UserAPI part of the API
	UserAPI UserAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"ApiV1AuditsBindingsGet",
			http.MethodGet,
			"/api/v1/audits/bindings",
			handleFunctions.AuditAPI.ApiV1AuditsBindingsGet,
		},
		{
			"ApiV1AuditsBindingsIdGet",
			http.MethodGet,
			"/api/v1/audits/bindings/:id",
			handleFunctions.AuditAPI.ApiV1AuditsBindingsIdGet,
		},
		{
			"ApiV1AuditsPoliciesGet",
			http.MethodGet,
			"/api/v1/audits/policies",
			handleFunctions.AuditAPI.ApiV1AuditsPoliciesGet,
		},
		{
			"ApiV1AuditsPoliciesIdGet",
			http.MethodGet,
			"/api/v1/audits/policies/:id",
			handleFunctions.AuditAPI.ApiV1AuditsPoliciesIdGet,
		},
		{
			"ApiV1AuthLoginPost",
			http.MethodPost,
			"/api/v1/auth/login",
			handleFunctions.AuthAPI.ApiV1AuthLoginPost,
		},
		{
			"ApiV1AuthLogoutPost",
			http.MethodPost,
			"/api/v1/auth/logout",
			handleFunctions.AuthAPI.ApiV1AuthLogoutPost,
		},
		{
			"ApiV1AuthMeGet",
			http.MethodGet,
			"/api/v1/auth/me",
			handleFunctions.AuthAPI.ApiV1AuthMeGet,
		},
		{
			"ApiV1AuthPasswordChangePost",
			http.MethodPost,
			"/api/v1/auth/password/change",
			handleFunctions.AuthAPI.ApiV1AuthPasswordChangePost,
		},
		{
			"ApiV1AuthRefreshPost",
			http.MethodPost,
			"/api/v1/auth/refresh",
			handleFunctions.AuthAPI.ApiV1AuthRefreshPost,
		},
		{
			"ApiV1AuthRegisterPost",
			http.MethodPost,
			"/api/v1/auth/register",
			handleFunctions.AuthAPI.ApiV1AuthRegisterPost,
		},
		{
			"ApiV1BindingsGet",
			http.MethodGet,
			"/api/v1/bindings",
			handleFunctions.BindingAPI.ApiV1BindingsGet,
		},
		{
			"ApiV1BindingsIdDelete",
			http.MethodDelete,
			"/api/v1/bindings/:id",
			handleFunctions.BindingAPI.ApiV1BindingsIdDelete,
		},
		{
			"ApiV1BindingsIdGet",
			http.MethodGet,
			"/api/v1/bindings/:id",
			handleFunctions.BindingAPI.ApiV1BindingsIdGet,
		},
		{
			"ApiV1BindingsPost",
			http.MethodPost,
			"/api/v1/bindings",
			handleFunctions.BindingAPI.ApiV1BindingsPost,
		},
		{
			"ApiV1PoliciesGet",
			http.MethodGet,
			"/api/v1/policies",
			handleFunctions.PolicyAPI.ApiV1PoliciesGet,
		},
		{
			"ApiV1PoliciesIdDelete",
			http.MethodDelete,
			"/api/v1/policies/:id",
			handleFunctions.PolicyAPI.ApiV1PoliciesIdDelete,
		},
		{
			"ApiV1PoliciesIdGet",
			http.MethodGet,
			"/api/v1/policies/:id",
			handleFunctions.PolicyAPI.ApiV1PoliciesIdGet,
		},
		{
			"ApiV1PoliciesIdPut",
			http.MethodPut,
			"/api/v1/policies/:id",
			handleFunctions.PolicyAPI.ApiV1PoliciesIdPut,
		},
		{
			"ApiV1PoliciesIdSecretsGet",
			http.MethodGet,
			"/api/v1/policies/:id/secrets",
			handleFunctions.PolicyAPI.ApiV1PoliciesIdSecretsGet,
		},
		{
			"ApiV1PoliciesPost",
			http.MethodPost,
			"/api/v1/policies",
			handleFunctions.PolicyAPI.ApiV1PoliciesPost,
		},
		{
			"ApiV1SecretsGet",
			http.MethodGet,
			"/api/v1/secrets",
			handleFunctions.SecretAPI.ApiV1SecretsGet,
		},
		{
			"ApiV1SecretsIdDelete",
			http.MethodDelete,
			"/api/v1/secrets/:id",
			handleFunctions.SecretAPI.ApiV1SecretsIdDelete,
		},
		{
			"ApiV1SecretsIdGet",
			http.MethodGet,
			"/api/v1/secrets/:id",
			handleFunctions.SecretAPI.ApiV1SecretsIdGet,
		},
		{
			"ApiV1SecretsIdPoliciesGet",
			http.MethodGet,
			"/api/v1/secrets/:id/policies",
			handleFunctions.SecretAPI.ApiV1SecretsIdPoliciesGet,
		},
		{
			"ApiV1SecretsIdPut",
			http.MethodPut,
			"/api/v1/secrets/:id",
			handleFunctions.SecretAPI.ApiV1SecretsIdPut,
		},
		{
			"ApiV1SecretsIdRotatePut",
			http.MethodPut,
			"/api/v1/secrets/:id/rotate",
			handleFunctions.SecretAPI.ApiV1SecretsIdRotatePut,
		},
		{
			"ApiV1SecretsPost",
			http.MethodPost,
			"/api/v1/secrets",
			handleFunctions.SecretAPI.ApiV1SecretsPost,
		},
		{
			"ApiV1UsersGet",
			http.MethodGet,
			"/api/v1/users",
			handleFunctions.UserAPI.ApiV1UsersGet,
		},
		{
			"ApiV1UsersIdDelete",
			http.MethodDelete,
			"/api/v1/users/:id",
			handleFunctions.UserAPI.ApiV1UsersIdDelete,
		},
		{
			"ApiV1UsersIdGet",
			http.MethodGet,
			"/api/v1/users/:id",
			handleFunctions.UserAPI.ApiV1UsersIdGet,
		},
		{
			"ApiV1UsersIdPut",
			http.MethodPut,
			"/api/v1/users/:id",
			handleFunctions.UserAPI.ApiV1UsersIdPut,
		},
		{
			"ApiV1UsersPost",
			http.MethodPost,
			"/api/v1/users",
			handleFunctions.UserAPI.ApiV1UsersPost,
		},
	}
}
