// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: auth_quey.proto

package pbv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSecretsRequest) Reset() {
	*x = GetAllSecretsRequest{}
	mi := &file_auth_quey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSecretsRequest) ProtoMessage() {}

func (x *GetAllSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_quey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSecretsRequest.ProtoReflect.Descriptor instead.
func (*GetAllSecretsRequest) Descriptor() ([]byte, []int) {
	return file_auth_quey_proto_rawDescGZIP(), []int{0}
}

type GetAllSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*Secret              `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSecretsResponse) Reset() {
	*x = GetAllSecretsResponse{}
	mi := &file_auth_quey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSecretsResponse) ProtoMessage() {}

func (x *GetAllSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_quey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSecretsResponse.ProtoReflect.Descriptor instead.
func (*GetAllSecretsResponse) Descriptor() ([]byte, []int) {
	return file_auth_quey_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllSecretsResponse) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type GetAllPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPoliciesRequest) Reset() {
	*x = GetAllPoliciesRequest{}
	mi := &file_auth_quey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPoliciesRequest) ProtoMessage() {}

func (x *GetAllPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_quey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPoliciesRequest.ProtoReflect.Descriptor instead.
func (*GetAllPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_auth_quey_proto_rawDescGZIP(), []int{2}
}

type GetAllPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyGroups  []*PolicyGroup         `protobuf:"bytes,1,rep,name=policy_groups,json=policyGroups,proto3" json:"policy_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPoliciesResponse) Reset() {
	*x = GetAllPoliciesResponse{}
	mi := &file_auth_quey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPoliciesResponse) ProtoMessage() {}

func (x *GetAllPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_quey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPoliciesResponse.ProtoReflect.Descriptor instead.
func (*GetAllPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_auth_quey_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllPoliciesResponse) GetPolicyGroups() []*PolicyGroup {
	if x != nil {
		return x.PolicyGroups
	}
	return nil
}

var File_auth_quey_proto protoreflect.FileDescriptor

const file_auth_quey_proto_rawDesc = "" +
	"\n" +
	"\x0fauth_quey.proto\x12\bproto.v1\x1a\vmodel.proto\"\x16\n" +
	"\x14GetAllSecretsRequest\"C\n" +
	"\x15GetAllSecretsResponse\x12*\n" +
	"\asecrets\x18\x01 \x03(\v2\x10.proto.v1.SecretR\asecrets\"\x17\n" +
	"\x15GetAllPoliciesRequest\"T\n" +
	"\x16GetAllPoliciesResponse\x12:\n" +
	"\rpolicy_groups\x18\x01 \x03(\v2\x15.proto.v1.PolicyGroupR\fpolicyGroups2\xb9\x01\n" +
	"\x10AuthQueryService\x12P\n" +
	"\rGetAllSecrets\x12\x1e.proto.v1.GetAllSecretsRequest\x1a\x1f.proto.v1.GetAllSecretsResponse\x12S\n" +
	"\x0eGetAllPolicies\x12\x1f.proto.v1.GetAllPoliciesRequest\x1a .proto.v1.GetAllPoliciesResponseB<Z:github.com/sis-shen/sup-iam/internal/pkg/proto/rpc/v2;pbv2b\x06proto3"

var (
	file_auth_quey_proto_rawDescOnce sync.Once
	file_auth_quey_proto_rawDescData []byte
)

func file_auth_quey_proto_rawDescGZIP() []byte {
	file_auth_quey_proto_rawDescOnce.Do(func() {
		file_auth_quey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_quey_proto_rawDesc), len(file_auth_quey_proto_rawDesc)))
	})
	return file_auth_quey_proto_rawDescData
}

var file_auth_quey_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auth_quey_proto_goTypes = []any{
	(*GetAllSecretsRequest)(nil),   // 0: proto.v1.GetAllSecretsRequest
	(*GetAllSecretsResponse)(nil),  // 1: proto.v1.GetAllSecretsResponse
	(*GetAllPoliciesRequest)(nil),  // 2: proto.v1.GetAllPoliciesRequest
	(*GetAllPoliciesResponse)(nil), // 3: proto.v1.GetAllPoliciesResponse
	(*Secret)(nil),                 // 4: proto.v1.Secret
	(*PolicyGroup)(nil),            // 5: proto.v1.PolicyGroup
}
var file_auth_quey_proto_depIdxs = []int32{
	4, // 0: proto.v1.GetAllSecretsResponse.secrets:type_name -> proto.v1.Secret
	5, // 1: proto.v1.GetAllPoliciesResponse.policy_groups:type_name -> proto.v1.PolicyGroup
	0, // 2: proto.v1.AuthQueryService.GetAllSecrets:input_type -> proto.v1.GetAllSecretsRequest
	2, // 3: proto.v1.AuthQueryService.GetAllPolicies:input_type -> proto.v1.GetAllPoliciesRequest
	1, // 4: proto.v1.AuthQueryService.GetAllSecrets:output_type -> proto.v1.GetAllSecretsResponse
	3, // 5: proto.v1.AuthQueryService.GetAllPolicies:output_type -> proto.v1.GetAllPoliciesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_quey_proto_init() }
func file_auth_quey_proto_init() {
	if File_auth_quey_proto != nil {
		return
	}
	file_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_quey_proto_rawDesc), len(file_auth_quey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_quey_proto_goTypes,
		DependencyIndexes: file_auth_quey_proto_depIdxs,
		MessageInfos:      file_auth_quey_proto_msgTypes,
	}.Build()
	File_auth_quey_proto = out.File
	file_auth_quey_proto_goTypes = nil
	file_auth_quey_proto_depIdxs = nil
}
