// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: auth_quey.proto

package pbv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthQueryService_GetAllSecrets_FullMethodName  = "/proto.v1.AuthQueryService/GetAllSecrets"
	AuthQueryService_GetAllPolicies_FullMethodName = "/proto.v1.AuthQueryService/GetAllPolicies"
)

// AuthQueryServiceClient is the client API for AuthQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthQueryServiceClient interface {
	GetAllSecrets(ctx context.Context, in *GetAllSecretsRequest, opts ...grpc.CallOption) (*GetAllSecretsResponse, error)
	GetAllPolicies(ctx context.Context, in *GetAllPoliciesRequest, opts ...grpc.CallOption) (*GetAllPoliciesResponse, error)
}

type authQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthQueryServiceClient(cc grpc.ClientConnInterface) AuthQueryServiceClient {
	return &authQueryServiceClient{cc}
}

func (c *authQueryServiceClient) GetAllSecrets(ctx context.Context, in *GetAllSecretsRequest, opts ...grpc.CallOption) (*GetAllSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllSecretsResponse)
	err := c.cc.Invoke(ctx, AuthQueryService_GetAllSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authQueryServiceClient) GetAllPolicies(ctx context.Context, in *GetAllPoliciesRequest, opts ...grpc.CallOption) (*GetAllPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllPoliciesResponse)
	err := c.cc.Invoke(ctx, AuthQueryService_GetAllPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthQueryServiceServer is the server API for AuthQueryService service.
// All implementations must embed UnimplementedAuthQueryServiceServer
// for forward compatibility.
type AuthQueryServiceServer interface {
	GetAllSecrets(context.Context, *GetAllSecretsRequest) (*GetAllSecretsResponse, error)
	GetAllPolicies(context.Context, *GetAllPoliciesRequest) (*GetAllPoliciesResponse, error)
	mustEmbedUnimplementedAuthQueryServiceServer()
}

// UnimplementedAuthQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthQueryServiceServer struct{}

func (UnimplementedAuthQueryServiceServer) GetAllSecrets(context.Context, *GetAllSecretsRequest) (*GetAllSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllSecrets not implemented")
}
func (UnimplementedAuthQueryServiceServer) GetAllPolicies(context.Context, *GetAllPoliciesRequest) (*GetAllPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllPolicies not implemented")
}
func (UnimplementedAuthQueryServiceServer) mustEmbedUnimplementedAuthQueryServiceServer() {}
func (UnimplementedAuthQueryServiceServer) testEmbeddedByValue()                          {}

// UnsafeAuthQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthQueryServiceServer will
// result in compilation errors.
type UnsafeAuthQueryServiceServer interface {
	mustEmbedUnimplementedAuthQueryServiceServer()
}

func RegisterAuthQueryServiceServer(s grpc.ServiceRegistrar, srv AuthQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthQueryService_ServiceDesc, srv)
}

func _AuthQueryService_GetAllSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthQueryServiceServer).GetAllSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthQueryService_GetAllSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthQueryServiceServer).GetAllSecrets(ctx, req.(*GetAllSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthQueryService_GetAllPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthQueryServiceServer).GetAllPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthQueryService_GetAllPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthQueryServiceServer).GetAllPolicies(ctx, req.(*GetAllPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthQueryService_ServiceDesc is the grpc.ServiceDesc for AuthQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.AuthQueryService",
	HandlerType: (*AuthQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllSecrets",
			Handler:    _AuthQueryService_GetAllSecrets_Handler,
		},
		{
			MethodName: "GetAllPolicies",
			Handler:    _AuthQueryService_GetAllPolicies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_quey.proto",
}
