/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

// RefreshResponse - 令牌刷新响应
type RefreshResponse struct {

	// 新的访问令牌
	AccessToken string `json:"access_token,omitempty"`

	// 访问令牌有效期（秒）
	ExpiresIn int64 `json:"expires_in,omitempty"`
}
