/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

// LoginRequest - 用户登录请求
type LoginRequest struct {

	// 用户名登录
	Username string `json:"username,omitempty"`

	// 手机号登录
	Phone string `json:"phone,omitempty"`

	// 邮箱登录
	Email string `json:"email,omitempty"`

	// 密码
	Password string `json:"password"`
}
