/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

import (
	"time"
)

type PolicyResponse struct {
	Id int64 `json:"id,omitempty"`

	InstanceId string `json:"instance_id,omitempty"`

	Name string `json:"name,omitempty"`

	Username string `json:"username,omitempty"`

	Description *string `json:"description,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// 策略内容（JSON格式）
	Content string `json:"content,omitempty"`
}
