/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

import (
	"time"
)

// User - IAM控制面用户实体
type User struct {

	// 用户唯一ID
	Id int64 `json:"id,omitempty"`

	// 实例标识，用于多租户隔离
	InstanceId string `json:"instance_id,omitempty" validate:"regexp=^[a-zA-Z0-9-_]{1,64}$"`

	// 用户名，全小写字母、数字、下划线，3-32字符
	Username string `json:"username" validate:"regexp=^[a-z0-9_]{3,32}$"`

	// 显示名称
	Nickname string `json:"nickname,omitempty"`

	// 用户状态枚举
	IsEnable int32 `json:"is_enable"`

	// 手机号，E.164格式
	Phone *string `json:"phone,omitempty" validate:"regexp=^\\\\+?[1-9]\\\\d{1,14}$"`

	// 邮箱地址
	Email *string `json:"email,omitempty"`

	// 管理员标识枚举
	IsAdmin int32 `json:"is_admin"`

	// 扩展字段影子，JSON格式存储扩展属性
	ExtendShadow *string `json:"extend_shadow,omitempty" gorm:"serializer:json"`

	// 最后登录时间
	LoggedAt *time.Time `json:"logged_at,omitempty"`

	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`

	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
