/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

// RefreshTokenRequest - 刷新访问令牌请求
type RefreshTokenRequest struct {

	// 刷新令牌
	RefreshToken string `json:"refresh_token"`
}
