/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

// IsEnable : 用户状态枚举
type IsEnable int32

// List of IsEnable
const (
	_0 IsEnable = 0
	_1 IsEnable = 1
)
