/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

// RegisterRequest - 用户注册请求
type RegisterRequest struct {

	// 用户名
	Username string `json:"username" validate:"regexp=^[a-z0-9_]{3,32}$"`

	// 密码
	Password string `json:"password"`

	// 邮箱
	Email *string `json:"email,omitempty"`

	// 手机号
	Phone *string `json:"phone,omitempty" validate:"regexp=^\\\\+?[1-9]\\\\d{1,14}$"`
}
