/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

// IsAdmin : 管理员标识枚举
type IsAdmin int32

// List of IsAdmin
const (
	_0 IsAdmin = 0
	_1 IsAdmin = 1
)
