/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

// LoginResponse - 登录成功响应
type LoginResponse struct {

	// 访问令牌(JWT)
	AccessToken string `json:"access_token,omitempty"`

	// 刷新令牌
	RefreshToken string `json:"refresh_token,omitempty"`

	// 访问令牌有效期（秒）
	ExpiresIn int64 `json:"expires_in,omitempty"`
}
