// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sis-shen/sup-iam/internal/iam-api-server/v1/service (interfaces: AuditCaseInterface)
//
// Generated by this command:
//
//	mockgen -destination=./mock/audit_case_mock.go -package=mock . AuditCaseInterface
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/model"
	repository "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditCaseInterface is a mock of AuditCaseInterface interface.
type MockAuditCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuditCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockAuditCaseInterfaceMockRecorder is the mock recorder for MockAuditCaseInterface.
type MockAuditCaseInterfaceMockRecorder struct {
	mock *MockAuditCaseInterface
}

// NewMockAuditCaseInterface creates a new mock instance.
func NewMockAuditCaseInterface(ctrl *gomock.Controller) *MockAuditCaseInterface {
	mock := &MockAuditCaseInterface{ctrl: ctrl}
	mock.recorder = &MockAuditCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditCaseInterface) EXPECT() *MockAuditCaseInterfaceMockRecorder {
	return m.recorder
}

// GetAuditBindingByID mocks base method.
func (m *MockAuditCaseInterface) GetAuditBindingByID(ctx context.Context, id string) (model.BindingAudit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditBindingByID", ctx, id)
	ret0, _ := ret[0].(model.BindingAudit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditBindingByID indicates an expected call of GetAuditBindingByID.
func (mr *MockAuditCaseInterfaceMockRecorder) GetAuditBindingByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditBindingByID", reflect.TypeOf((*MockAuditCaseInterface)(nil).GetAuditBindingByID), ctx, id)
}

// GetAuditBindingList mocks base method.
func (m *MockAuditCaseInterface) GetAuditBindingList(ctx context.Context, query repository.PageQuery) (repository.PageResult[*model.BindingAudit], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditBindingList", ctx, query)
	ret0, _ := ret[0].(repository.PageResult[*model.BindingAudit])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditBindingList indicates an expected call of GetAuditBindingList.
func (mr *MockAuditCaseInterfaceMockRecorder) GetAuditBindingList(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditBindingList", reflect.TypeOf((*MockAuditCaseInterface)(nil).GetAuditBindingList), ctx, query)
}

// GetAuditPolicyByID mocks base method.
func (m *MockAuditCaseInterface) GetAuditPolicyByID(ctx context.Context, id string) (model.PolicyAudit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditPolicyByID", ctx, id)
	ret0, _ := ret[0].(model.PolicyAudit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditPolicyByID indicates an expected call of GetAuditPolicyByID.
func (mr *MockAuditCaseInterfaceMockRecorder) GetAuditPolicyByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditPolicyByID", reflect.TypeOf((*MockAuditCaseInterface)(nil).GetAuditPolicyByID), ctx, id)
}

// GetAuditPolicyList mocks base method.
func (m *MockAuditCaseInterface) GetAuditPolicyList(ctx context.Context, query repository.PageQuery) (repository.PageResult[*model.PolicyAudit], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditPolicyList", ctx, query)
	ret0, _ := ret[0].(repository.PageResult[*model.PolicyAudit])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditPolicyList indicates an expected call of GetAuditPolicyList.
func (mr *MockAuditCaseInterfaceMockRecorder) GetAuditPolicyList(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditPolicyList", reflect.TypeOf((*MockAuditCaseInterface)(nil).GetAuditPolicyList), ctx, query)
}
