// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sis-shen/sup-iam/internal/iam-api-server/v1/service (interfaces: AuthCaseInterface)
//
// Generated by this command:
//
//	mockgen -destination=./mock/auth_case_mock.go -package=mock . AuthCaseInterface
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	model "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthCaseInterface is a mock of AuthCaseInterface interface.
type MockAuthCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthCaseInterfaceMockRecorder is the mock recorder for MockAuthCaseInterface.
type MockAuthCaseInterfaceMockRecorder struct {
	mock *MockAuthCaseInterface
}

// NewMockAuthCaseInterface creates a new mock instance.
func NewMockAuthCaseInterface(ctrl *gomock.Controller) *MockAuthCaseInterface {
	mock := &MockAuthCaseInterface{ctrl: ctrl}
	mock.recorder = &MockAuthCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthCaseInterface) EXPECT() *MockAuthCaseInterfaceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthCaseInterface) Login(ctx *gin.Context, user *model.User) (*model.User, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, user)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Login indicates an expected call of Login.
func (mr *MockAuthCaseInterfaceMockRecorder) Login(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthCaseInterface)(nil).Login), ctx, user)
}

// Logout mocks base method.
func (m *MockAuthCaseInterface) Logout(ctx *gin.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthCaseInterfaceMockRecorder) Logout(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthCaseInterface)(nil).Logout), ctx)
}

// RefreshToken mocks base method.
func (m *MockAuthCaseInterface) RefreshToken(ctx *gin.Context, userID, userName string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, userID, userName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthCaseInterfaceMockRecorder) RefreshToken(ctx, userID, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthCaseInterface)(nil).RefreshToken), ctx, userID, userName)
}

// Register mocks base method.
func (m *MockAuthCaseInterface) Register(ctx *gin.Context, user *model.User) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, user)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthCaseInterfaceMockRecorder) Register(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthCaseInterface)(nil).Register), ctx, user)
}
