// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sis-shen/sup-iam/internal/iam-api-server/v1/service (interfaces: BindingCaseInterface)
//
// Generated by this command:
//
//	mockgen -destination=./mock/binding_case_mock.go -package=mock . BindingCaseInterface
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/model"
	repository "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockBindingCaseInterface is a mock of BindingCaseInterface interface.
type MockBindingCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBindingCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockBindingCaseInterfaceMockRecorder is the mock recorder for MockBindingCaseInterface.
type MockBindingCaseInterfaceMockRecorder struct {
	mock *MockBindingCaseInterface
}

// NewMockBindingCaseInterface creates a new mock instance.
func NewMockBindingCaseInterface(ctrl *gomock.Controller) *MockBindingCaseInterface {
	mock := &MockBindingCaseInterface{ctrl: ctrl}
	mock.recorder = &MockBindingCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBindingCaseInterface) EXPECT() *MockBindingCaseInterfaceMockRecorder {
	return m.recorder
}

// CreateBinding mocks base method.
func (m *MockBindingCaseInterface) CreateBinding(ctx context.Context, binding *model.Binding) (*model.Binding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBinding", ctx, binding)
	ret0, _ := ret[0].(*model.Binding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBinding indicates an expected call of CreateBinding.
func (mr *MockBindingCaseInterfaceMockRecorder) CreateBinding(ctx, binding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBinding", reflect.TypeOf((*MockBindingCaseInterface)(nil).CreateBinding), ctx, binding)
}

// DeleteBinding mocks base method.
func (m *MockBindingCaseInterface) DeleteBinding(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBinding", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBinding indicates an expected call of DeleteBinding.
func (mr *MockBindingCaseInterfaceMockRecorder) DeleteBinding(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBinding", reflect.TypeOf((*MockBindingCaseInterface)(nil).DeleteBinding), ctx, id)
}

// GetBindingById mocks base method.
func (m *MockBindingCaseInterface) GetBindingById(ctx context.Context, id string) (*model.Binding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBindingById", ctx, id)
	ret0, _ := ret[0].(*model.Binding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBindingById indicates an expected call of GetBindingById.
func (mr *MockBindingCaseInterfaceMockRecorder) GetBindingById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBindingById", reflect.TypeOf((*MockBindingCaseInterface)(nil).GetBindingById), ctx, id)
}

// GetBindingListByUserID mocks base method.
func (m *MockBindingCaseInterface) GetBindingListByUserID(ctx context.Context, id string, query repository.PageQuery) (repository.PageResult[*model.Binding], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBindingListByUserID", ctx, id, query)
	ret0, _ := ret[0].(repository.PageResult[*model.Binding])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBindingListByUserID indicates an expected call of GetBindingListByUserID.
func (mr *MockBindingCaseInterfaceMockRecorder) GetBindingListByUserID(ctx, id, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBindingListByUserID", reflect.TypeOf((*MockBindingCaseInterface)(nil).GetBindingListByUserID), ctx, id, query)
}
