// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sis-shen/sup-iam/internal/iam-api-server/v1/service (interfaces: PolicyCaseInterface)
//
// Generated by this command:
//
//	mockgen -destination=./mock/policy_case_mock.go -package=mock . PolicyCaseInterface
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/model"
	repository "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockPolicyCaseInterface is a mock of PolicyCaseInterface interface.
type MockPolicyCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockPolicyCaseInterfaceMockRecorder is the mock recorder for MockPolicyCaseInterface.
type MockPolicyCaseInterfaceMockRecorder struct {
	mock *MockPolicyCaseInterface
}

// NewMockPolicyCaseInterface creates a new mock instance.
func NewMockPolicyCaseInterface(ctrl *gomock.Controller) *MockPolicyCaseInterface {
	mock := &MockPolicyCaseInterface{ctrl: ctrl}
	mock.recorder = &MockPolicyCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyCaseInterface) EXPECT() *MockPolicyCaseInterfaceMockRecorder {
	return m.recorder
}

// CreatePolicy mocks base method.
func (m *MockPolicyCaseInterface) CreatePolicy(ctx context.Context, policy *model.Policy) (*model.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePolicy", ctx, policy)
	ret0, _ := ret[0].(*model.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePolicy indicates an expected call of CreatePolicy.
func (mr *MockPolicyCaseInterfaceMockRecorder) CreatePolicy(ctx, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePolicy", reflect.TypeOf((*MockPolicyCaseInterface)(nil).CreatePolicy), ctx, policy)
}

// DeletePolicy mocks base method.
func (m *MockPolicyCaseInterface) DeletePolicy(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePolicy", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePolicy indicates an expected call of DeletePolicy.
func (mr *MockPolicyCaseInterfaceMockRecorder) DeletePolicy(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePolicy", reflect.TypeOf((*MockPolicyCaseInterface)(nil).DeletePolicy), ctx, id)
}

// GetPolicyBindingSecretList mocks base method.
func (m *MockPolicyCaseInterface) GetPolicyBindingSecretList(ctx context.Context, id string, query repository.PageQuery) (repository.PageResult[*model.Secret], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicyBindingSecretList", ctx, id, query)
	ret0, _ := ret[0].(repository.PageResult[*model.Secret])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicyBindingSecretList indicates an expected call of GetPolicyBindingSecretList.
func (mr *MockPolicyCaseInterfaceMockRecorder) GetPolicyBindingSecretList(ctx, id, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicyBindingSecretList", reflect.TypeOf((*MockPolicyCaseInterface)(nil).GetPolicyBindingSecretList), ctx, id, query)
}

// GetPolicyByID mocks base method.
func (m *MockPolicyCaseInterface) GetPolicyByID(ctx context.Context, id string) (*model.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicyByID", ctx, id)
	ret0, _ := ret[0].(*model.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicyByID indicates an expected call of GetPolicyByID.
func (mr *MockPolicyCaseInterfaceMockRecorder) GetPolicyByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicyByID", reflect.TypeOf((*MockPolicyCaseInterface)(nil).GetPolicyByID), ctx, id)
}

// GetPolicyList mocks base method.
func (m *MockPolicyCaseInterface) GetPolicyList(ctx context.Context, id string, query repository.PageQuery) (repository.PageResult[*model.Policy], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicyList", ctx, id, query)
	ret0, _ := ret[0].(repository.PageResult[*model.Policy])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicyList indicates an expected call of GetPolicyList.
func (mr *MockPolicyCaseInterfaceMockRecorder) GetPolicyList(ctx, id, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicyList", reflect.TypeOf((*MockPolicyCaseInterface)(nil).GetPolicyList), ctx, id, query)
}

// UpdatePolicy mocks base method.
func (m *MockPolicyCaseInterface) UpdatePolicy(ctx context.Context, policy *model.Policy) (*model.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePolicy", ctx, policy)
	ret0, _ := ret[0].(*model.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePolicy indicates an expected call of UpdatePolicy.
func (mr *MockPolicyCaseInterfaceMockRecorder) UpdatePolicy(ctx, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePolicy", reflect.TypeOf((*MockPolicyCaseInterface)(nil).UpdatePolicy), ctx, policy)
}
