// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sis-shen/sup-iam/internal/iam-api-server/v1/service (interfaces: SecretCaseInterface)
//
// Generated by this command:
//
//	mockgen -destination=./mock/secret_case_mock.go -package=mock . SecretCaseInterface
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/model"
	repository "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretCaseInterface is a mock of SecretCaseInterface interface.
type MockSecretCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSecretCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockSecretCaseInterfaceMockRecorder is the mock recorder for MockSecretCaseInterface.
type MockSecretCaseInterfaceMockRecorder struct {
	mock *MockSecretCaseInterface
}

// NewMockSecretCaseInterface creates a new mock instance.
func NewMockSecretCaseInterface(ctrl *gomock.Controller) *MockSecretCaseInterface {
	mock := &MockSecretCaseInterface{ctrl: ctrl}
	mock.recorder = &MockSecretCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretCaseInterface) EXPECT() *MockSecretCaseInterfaceMockRecorder {
	return m.recorder
}

// CreateSecret mocks base method.
func (m *MockSecretCaseInterface) CreateSecret(ctx context.Context, secret *model.Secret) (*model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecret", ctx, secret)
	ret0, _ := ret[0].(*model.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MockSecretCaseInterfaceMockRecorder) CreateSecret(ctx, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MockSecretCaseInterface)(nil).CreateSecret), ctx, secret)
}

// DeleteSecret mocks base method.
func (m *MockSecretCaseInterface) DeleteSecret(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecret", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockSecretCaseInterfaceMockRecorder) DeleteSecret(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MockSecretCaseInterface)(nil).DeleteSecret), ctx, id)
}

// GenerateAccessKey mocks base method.
func (m *MockSecretCaseInterface) GenerateAccessKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateAccessKey indicates an expected call of GenerateAccessKey.
func (mr *MockSecretCaseInterfaceMockRecorder) GenerateAccessKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessKey", reflect.TypeOf((*MockSecretCaseInterface)(nil).GenerateAccessKey))
}

// GenerateSecretKey mocks base method.
func (m *MockSecretCaseInterface) GenerateSecretKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSecretKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateSecretKey indicates an expected call of GenerateSecretKey.
func (mr *MockSecretCaseInterfaceMockRecorder) GenerateSecretKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSecretKey", reflect.TypeOf((*MockSecretCaseInterface)(nil).GenerateSecretKey))
}

// GetAllPolicies mocks base method.
func (m *MockSecretCaseInterface) GetAllPolicies(ctx context.Context) (map[string][]*model.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPolicies", ctx)
	ret0, _ := ret[0].(map[string][]*model.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPolicies indicates an expected call of GetAllPolicies.
func (mr *MockSecretCaseInterfaceMockRecorder) GetAllPolicies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPolicies", reflect.TypeOf((*MockSecretCaseInterface)(nil).GetAllPolicies), ctx)
}

// GetAllSecrets mocks base method.
func (m *MockSecretCaseInterface) GetAllSecrets(ctx context.Context) ([]*model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSecrets", ctx)
	ret0, _ := ret[0].([]*model.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSecrets indicates an expected call of GetAllSecrets.
func (mr *MockSecretCaseInterfaceMockRecorder) GetAllSecrets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSecrets", reflect.TypeOf((*MockSecretCaseInterface)(nil).GetAllSecrets), ctx)
}

// GetSecretBindingPolicy mocks base method.
func (m *MockSecretCaseInterface) GetSecretBindingPolicy(ctx context.Context, id string, query repository.PageQuery) (repository.PageResult[*model.Policy], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretBindingPolicy", ctx, id, query)
	ret0, _ := ret[0].(repository.PageResult[*model.Policy])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretBindingPolicy indicates an expected call of GetSecretBindingPolicy.
func (mr *MockSecretCaseInterfaceMockRecorder) GetSecretBindingPolicy(ctx, id, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretBindingPolicy", reflect.TypeOf((*MockSecretCaseInterface)(nil).GetSecretBindingPolicy), ctx, id, query)
}

// GetSecretByAK mocks base method.
func (m *MockSecretCaseInterface) GetSecretByAK(ctx context.Context, ak string) (*model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretByAK", ctx, ak)
	ret0, _ := ret[0].(*model.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretByAK indicates an expected call of GetSecretByAK.
func (mr *MockSecretCaseInterfaceMockRecorder) GetSecretByAK(ctx, ak any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretByAK", reflect.TypeOf((*MockSecretCaseInterface)(nil).GetSecretByAK), ctx, ak)
}

// GetSecretByID mocks base method.
func (m *MockSecretCaseInterface) GetSecretByID(ctx context.Context, id string) (*model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretByID", ctx, id)
	ret0, _ := ret[0].(*model.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretByID indicates an expected call of GetSecretByID.
func (mr *MockSecretCaseInterfaceMockRecorder) GetSecretByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretByID", reflect.TypeOf((*MockSecretCaseInterface)(nil).GetSecretByID), ctx, id)
}

// GetSecretList mocks base method.
func (m *MockSecretCaseInterface) GetSecretList(ctx context.Context, id string, query repository.PageQuery) (repository.PageResult[*model.Secret], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretList", ctx, id, query)
	ret0, _ := ret[0].(repository.PageResult[*model.Secret])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretList indicates an expected call of GetSecretList.
func (mr *MockSecretCaseInterfaceMockRecorder) GetSecretList(ctx, id, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretList", reflect.TypeOf((*MockSecretCaseInterface)(nil).GetSecretList), ctx, id, query)
}

// RotateSecret mocks base method.
func (m *MockSecretCaseInterface) RotateSecret(ctx context.Context, id string) (*model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateSecret", ctx, id)
	ret0, _ := ret[0].(*model.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateSecret indicates an expected call of RotateSecret.
func (mr *MockSecretCaseInterfaceMockRecorder) RotateSecret(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateSecret", reflect.TypeOf((*MockSecretCaseInterface)(nil).RotateSecret), ctx, id)
}

// UpdateSecret mocks base method.
func (m *MockSecretCaseInterface) UpdateSecret(ctx context.Context, arg1 *model.Secret) (*model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, arg1)
	ret0, _ := ret[0].(*model.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockSecretCaseInterfaceMockRecorder) UpdateSecret(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockSecretCaseInterface)(nil).UpdateSecret), ctx, arg1)
}

// VerifySecret mocks base method.
func (m *MockSecretCaseInterface) VerifySecret(secret, payload, hashedStr string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySecret", secret, payload, hashedStr)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifySecret indicates an expected call of VerifySecret.
func (mr *MockSecretCaseInterfaceMockRecorder) VerifySecret(secret, payload, hashedStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySecret", reflect.TypeOf((*MockSecretCaseInterface)(nil).VerifySecret), secret, payload, hashedStr)
}
