/*
 * IAM API Data Plane
 *
 * 身份与访问管理系统数据面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

import (
	"github.com/gin-gonic/gin"
)

type AuthVerifyAPI struct {
}

// Post /auth/v1/verify
// 鉴权验证 
func (api *AuthVerifyAPI) VerifyRequest(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

