/*
 * IAM API Data Plane
 *
 * 身份与访问管理系统数据面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

// VerifyResponse - 鉴权结果
type VerifyResponse struct {

	Allowed bool `json:"allowed,omitempty"`

	Reason *string `json:"reason,omitempty"`

	HttpCode *int32 `json:"http_code,omitempty"`

	MatchedPolicies []string `json:"matched_policies,omitempty"`
}
