/*
 * IAM API Data Plane
 *
 * 身份与访问管理系统数据面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamauthserver

import (
	"github.com/gin-gonic/gin"
	"github.com/sis-shen/sup-iam/internal/iam-auth-server/v1/service"
	"github.com/sis-shen/sup-iam/internal/pkg/log"
	"net/http"
	"strconv"
)

type AuthVerifyAPI struct {
	service service.AuthCaseInterface
	logger  log.Logger
}

var (
	AllowReason = "allowed"
	DenyReason  = "no policy allowed"
)

func NewAuthVerifyAPI(service service.AuthCaseInterface, logger log.Logger) *AuthVerifyAPI {
	return &AuthVerifyAPI{
		service: service,
		logger:  logger,
	}
}

// Post /auth/v1/verify
// 鉴权验证
func (api *AuthVerifyAPI) VerifyRequest(c *gin.Context) {
	logger := api.logger.WithValues("func", "VerifyRequest")
	logger.Info("Received get verify request")

	req := &VerifyRequest{}
	if err := c.ShouldBindJSON(req); err != nil {
		log.Warnf("Bind json err: %v", err)
		errRsp := ErrorResponse{
			Error:            "Parse request body failed",
			ErrorDescription: err.Error(),
		}
		c.JSON(http.StatusBadRequest, errRsp)
		return
	}
	timeStr := strconv.FormatInt(req.Timestamp, 10)
	canonicalString := api.service.BuildCanonicalString(req.AccessKey, req.Method, req.Path, req.ContentHash, timeStr)

	ok, secret, err := api.service.VerifySecretKey(c, req.AccessKey, canonicalString, req.Signature)
	if err != nil {
		log.Warnf("Verify secret err: %v", err)
		errRsp := ErrorResponse{
			Error:            "verify secret error",
			ErrorDescription: err.Error(),
		}
		c.JSON(http.StatusBadRequest, errRsp)
		return
	}
	if !ok {
		errMsg := "unknown error"
		if err != nil {
			errMsg = err.Error()
		}
		log.Warnf("invalid secret: %v", errMsg)
		errRsp := ErrorResponse{
			Error:            "verify secret failed",
			ErrorDescription: errMsg,
		}
		c.JSON(http.StatusBadRequest, errRsp)
		return
	}

	if secret.AccessKey != req.AccessKey {
		errMsg := "unknown error"
		if err != nil {
			errMsg = err.Error()
		}
		logger.Warnf("verify secret access key err: %v", errMsg)
		errRsp := ErrorResponse{
			Error:            "verify secret access key error",
			ErrorDescription: errMsg,
		}
		c.JSON(http.StatusBadRequest, errRsp)
		return
	}

	ok, matched, err := api.service.Authorize(c, strconv.FormatUint(secret.ID, 10), secret.AccessKey, req.Path, req.Method)
	if err != nil {
		logger.Warnf("Authorize err: %v", err)
		errRsp := ErrorResponse{
			Error:            "authorize error",
			ErrorDescription: err.Error(),
		}
		c.JSON(http.StatusBadRequest, errRsp)
		return
	}
	if !ok {
		resp := VerifyResponse{
			Allowed:         false,
			Reason:          &DenyReason,
			HttpCode:        nil,
			MatchedPolicies: nil,
		}
		c.JSON(403, resp)
		return
	}

	resp := VerifyResponse{
		Allowed:         true,
		Reason:          &AllowReason,
		HttpCode:        nil,
		MatchedPolicies: matched,
	}
	c.JSON(200, resp)
}
