/*
 * IAM API Data Plane
 *
 * 身份与访问管理系统数据面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamauthserver

// VerifyRequest - 数据面请求鉴权
type VerifyRequest struct {
	AccessKey string `json:"access_key"`

	Method string `json:"method"`

	Path string `json:"path"`

	ContentHash string `json:"content_hash"`

	Timestamp int64 `json:"timestamp"`

	Signature string `json:"signature"`
}
