// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sis-shen/sup-iam/internal/iam-auth-server/v1/rpc (interfaces: RpcClientInterface)
//
// Generated by this command:
//
//	mockgen -destination=./mock/rpc_client_mock.go -package=mock . RpcClientInterface
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRpcClientInterface is a mock of RpcClientInterface interface.
type MockRpcClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRpcClientInterfaceMockRecorder
	isgomock struct{}
}

// MockRpcClientInterfaceMockRecorder is the mock recorder for MockRpcClientInterface.
type MockRpcClientInterfaceMockRecorder struct {
	mock *MockRpcClientInterface
}

// NewMockRpcClientInterface creates a new mock instance.
func NewMockRpcClientInterface(ctrl *gomock.Controller) *MockRpcClientInterface {
	mock := &MockRpcClientInterface{ctrl: ctrl}
	mock.recorder = &MockRpcClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRpcClientInterface) EXPECT() *MockRpcClientInterfaceMockRecorder {
	return m.recorder
}

// GetPolicyListBySecretID mocks base method.
func (m *MockRpcClientInterface) GetPolicyListBySecretID(ctx context.Context, secretID string) ([]*model.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicyListBySecretID", ctx, secretID)
	ret0, _ := ret[0].([]*model.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicyListBySecretID indicates an expected call of GetPolicyListBySecretID.
func (mr *MockRpcClientInterfaceMockRecorder) GetPolicyListBySecretID(ctx, secretID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicyListBySecretID", reflect.TypeOf((*MockRpcClientInterface)(nil).GetPolicyListBySecretID), ctx, secretID)
}

// GetSecretByAK mocks base method.
func (m *MockRpcClientInterface) GetSecretByAK(ctx context.Context, accessKey string) (*model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretByAK", ctx, accessKey)
	ret0, _ := ret[0].(*model.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretByAK indicates an expected call of GetSecretByAK.
func (mr *MockRpcClientInterfaceMockRecorder) GetSecretByAK(ctx, accessKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretByAK", reflect.TypeOf((*MockRpcClientInterface)(nil).GetSecretByAK), ctx, accessKey)
}
