// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sis-shen/sup-iam/internal/iam-auth-server/v1/service (interfaces: AuthCaseInterface)
//
// Generated by this command:
//
//	mockgen -destination=./mock/auth_case_mock.go -package=mock . AuthCaseInterface
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthCaseInterface is a mock of AuthCaseInterface interface.
type MockAuthCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthCaseInterfaceMockRecorder is the mock recorder for MockAuthCaseInterface.
type MockAuthCaseInterfaceMockRecorder struct {
	mock *MockAuthCaseInterface
}

// NewMockAuthCaseInterface creates a new mock instance.
func NewMockAuthCaseInterface(ctrl *gomock.Controller) *MockAuthCaseInterface {
	mock := &MockAuthCaseInterface{ctrl: ctrl}
	mock.recorder = &MockAuthCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthCaseInterface) EXPECT() *MockAuthCaseInterfaceMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockAuthCaseInterface) Authorize(ctx context.Context, secretID, accessKey, path, method string) (bool, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, secretID, accessKey, path, method)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Authorize indicates an expected call of Authorize.
func (mr *MockAuthCaseInterfaceMockRecorder) Authorize(ctx, secretID, accessKey, path, method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockAuthCaseInterface)(nil).Authorize), ctx, secretID, accessKey, path, method)
}

// BuildCanonicalString mocks base method.
func (m *MockAuthCaseInterface) BuildCanonicalString(accessKey, method, path, contentHash, timeStamp string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildCanonicalString", accessKey, method, path, contentHash, timeStamp)
	ret0, _ := ret[0].(string)
	return ret0
}

// BuildCanonicalString indicates an expected call of BuildCanonicalString.
func (mr *MockAuthCaseInterfaceMockRecorder) BuildCanonicalString(accessKey, method, path, contentHash, timeStamp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildCanonicalString", reflect.TypeOf((*MockAuthCaseInterface)(nil).BuildCanonicalString), accessKey, method, path, contentHash, timeStamp)
}

// VerifySecretKey mocks base method.
func (m *MockAuthCaseInterface) VerifySecretKey(ctx context.Context, accessKey, canonicalString, signature string) (bool, *model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySecretKey", ctx, accessKey, canonicalString, signature)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*model.Secret)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// VerifySecretKey indicates an expected call of VerifySecretKey.
func (mr *MockAuthCaseInterfaceMockRecorder) VerifySecretKey(ctx, accessKey, canonicalString, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySecretKey", reflect.TypeOf((*MockAuthCaseInterface)(nil).VerifySecretKey), ctx, accessKey, canonicalString, signature)
}
