/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

import (
	"github.com/gin-gonic/gin"
	"github.com/sis-shen/sup-iam/internal/iam-api-server/v1/model"
	"github.com/sis-shen/sup-iam/internal/iam-api-server/v1/service"
	"github.com/sis-shen/sup-iam/internal/pkg/log"
	"time"
)

type UserAPI struct {
	userCase service.UserCaseInterface
	logger   log.Logger
}

func NewUserAPI(userCase service.UserCaseInterface, logger log.Logger) *UserAPI {
	if logger == nil {
		logger = log.WithName("UserAPI")
	}
	return &UserAPI{userCase: userCase, logger: logger}
}

// Get /api/v1/users
// 获取用户列表
func (api *UserAPI) ApiV1UsersGet(c *gin.Context) {
	logger := api.logger.WithValues("func", "ApiV1UsersGet")
	logger.Info("Received get users request")

	logger.Debugf("Request headers: %v", c.Request.Header)
	logger.Debugf("Query params: %v", c.Request.URL.Query())
	// 1. 解析请求参数
	query, err := service.ParseListQuery(c)
	if err != nil {
		logger.Warnf("Error parsing query params: %v", err)
		errRsp := ErrorResponse{
			Error:            ParamParseError,
			ErrorDescription: err.Error(),
		}
		c.JSON(400, errRsp)
		return
	}

	logger.Debugw("Parsed query: ", "limit", query.Limit,
		"cursor", query.Cursor, "order", query.Order, "order_by", query.OrderBy)

	// 2. 从数据库获取数据
	logger.Infow("Fetching users", "limit", query.Limit,
		"cursor", query.Cursor, "order", query.Order, "order_by", query.OrderBy)
	res, err := api.userCase.GetUserList(c, query)

	if err != nil {
		logger.Warnf("Error getting users from service: %v", err)
		errRsp := ErrorResponse{
			Error:            RepositoryError,
			ErrorDescription: err.Error(),
		}
		c.JSON(500, errRsp)
		return
	}

	logger.Infow("Successfully fetched users", "count", len(res.Items),
		"next", res.Next, "total", res.Total)

	items, err := parseUserModelList(res.Items)
	if err != nil {
		logger.Warnf("Error parsing user model: %v", err)
		errRsp := ErrorResponse{
			Error:            RepositoryError,
			ErrorDescription: err.Error(),
		}
		c.JSON(500, errRsp)
		return
	}

	logger.Debugw("Parse user list", "items_len", len(items))
	data := UserListResponse{
		Items:    items,
		Page:     service.GetPage(c),
		PageSize: service.GetPageSize(c),
		Total:    res.Total,
		Next:     res.Next,
	}

	c.JSON(200, data)
	logger.Info("Get users request completed successfully")
}

// Delete /api/v1/users/:id
// 删除用户
func (api *UserAPI) ApiV1UsersIdDelete(c *gin.Context) {
	logger := api.logger.WithValues("func", "ApiV1UsersIdDelete")
	logger.Info("Received delete users request")
	// 解析参数
	id := c.Param("id")

	if id == "" {
		logger.Warnf("Error parsing user id: id not found")
		errRsp := ErrorResponse{
			Error:            ParamParseError,
			ErrorDescription: "id not found",
		}
		c.JSON(400, errRsp)
		return
	}

	logger.Debugw("Parsing user id", "id", id)

	// 执行操作
	logger.Infow("Deleting user", "id", id)
	err := api.userCase.DeleteUser(c, id)
	if err != nil {
		logger.Warnf("Error deleting user: %v", err)
		errRsp := ErrorResponse{
			Error:            RepositoryError,
			ErrorDescription: err.Error(),
		}
		c.JSON(500, errRsp)
		return
	}

	c.JSON(200, "")
	logger.Info("User deleted successfully")

}

// Get /api/v1/users/:id
// 获取指定用户信息
func (api *UserAPI) ApiV1UsersIdGet(c *gin.Context) {
	logger := api.logger.WithValues("func", "ApiV1UsersIdGet")
	logger.Info("Received get user request")
	// 解析参数
	id := c.Param("id")

	if id == "" {
		logger.Warnf("Error parsing user id: id not found")
		errRsp := ErrorResponse{
			Error:            ParamParseError,
			ErrorDescription: "id not found",
		}
		c.JSON(400, errRsp)
		return
	}

	logger.Debugw("Parsing user id", "id", id)

	// 执行操作
	logger.Infow("Getting user", "id", id)

	usr, err := api.userCase.GetUserByID(c, id)

	if err != nil {
		logger.Warnf("Error getting user: %v", err)
		errRsp := ErrorResponse{
			Error:            RepositoryError,
			ErrorDescription: err.Error(),
		}
		c.JSON(500, errRsp)
		return
	}

	c.JSON(200, parseUserModel(*usr))
	logger.Info("User got successfully")
}

// Put /api/v1/users/:id
// 更新用户字段
func (api *UserAPI) ApiV1UsersIdPut(c *gin.Context) {
	logger := api.logger.WithValues("func", "ApiV1UsersIdPut")
	logger.Info("Received update user request")
	// 解析参数
	id := c.Param("id")

	if id == "" {
		logger.Warnf("Error parsing user id: id not found")
		errRsp := ErrorResponse{
			Error:            ParamParseError,
			ErrorDescription: "id not found",
		}
		c.JSON(400, errRsp)
		return
	}

	res := UpdateUserRequest{}
	if err := c.ShouldBindBodyWithJSON(&res); err != nil {
		logger.Warnw("Error parsing body", "err", err)
		errRsp := ErrorResponse{
			Error:            ParamParseError,
			ErrorDescription: err.Error(),
		}
		c.JSON(400, errRsp)
		return
	}

	modelUser, err := api.userCase.GetUserByID(c, id)
	if err != nil {
		logger.Warnf("Error getting users from service: %v", err)
		errRsp := ErrorResponse{
			Error:            RepositoryError,
			ErrorDescription: err.Error(),
		}
		c.JSON(500, errRsp)
		return
	}

	// 预载用户字段
	if res.Nickname != "" && res.Nickname != modelUser.Nickname {
		modelUser.Nickname = res.Nickname
	}

	if res.Phone != nil && res.Phone != modelUser.Phone {
		modelUser.Phone = res.Phone
	}

	if res.Email != nil && res.Email != modelUser.Email {
		modelUser.Email = res.Email
	}

	if res.IsEnable >= 0 && res.IsEnable <= 1 {
		modelUser.IsEnable = uint8(res.IsEnable)
	}

	if res.IsAdmin >= 0 && res.IsAdmin <= 1 {
		modelUser.IsAdmin = uint8(res.IsAdmin)
	}

	if res.Password != nil && api.userCase.VerifyPassword(*res.Password, modelUser.PasswordHash) != nil {
		modelUser.PasswordHash, err = api.userCase.HashPassword(*res.Password)
		if err != nil {
			logger.Warnf("Error hashing password: %v", err)
			errRsp := ErrorResponse{
				Error:            InternalError,
				ErrorDescription: err.Error(),
			}
			c.JSON(500, errRsp)
			return
		}
	}

	if res.ExtendShadow != modelUser.ExtendShadow {
		modelUser.ExtendShadow = res.ExtendShadow
	}

	user, err := api.userCase.UpdateUser(c, modelUser)
	if err != nil {
		logger.Warnf("Error updating user: %v", err)
		errRsp := ErrorResponse{
			Error:            RepositoryError,
			ErrorDescription: err.Error(),
		}
		c.JSON(500, errRsp)
		return
	}

	rsp := parseUserModel(*user)

	c.JSON(200, rsp)
	logger.Info("User updated successfully")

}

// Post /api/v1/users
// 创建用户
func (api *UserAPI) ApiV1UsersPost(c *gin.Context) {
	logger := api.logger.WithValues("func", "ApiV1UsersIdPut")
	logger.Info("Received create user request")

	res := CreateUserRequest{}
	if err := c.ShouldBindBodyWithJSON(&res); err != nil {
		logger.Warnw("Error parsing body", "err", err)
		errRsp := ErrorResponse{
			Error:            ParamParseError,
			ErrorDescription: err.Error(),
		}
		c.JSON(400, errRsp)
		return
	}

	passwordHash, err := api.userCase.HashPassword(res.Password)
	if err != nil {
		logger.Warnw("Error hashing password", "err", err)
		errRsp := ErrorResponse{
			Error:            InternalError,
			ErrorDescription: err.Error(),
		}
		c.JSON(500, errRsp)
		return
	}
	nowTime := time.Now()
	instanceID := service.GenerateInstanceID()
	modelUser := model.User{
		InstanceID:   instanceID,
		Username:     res.Username,
		Nickname:     res.Nickname,
		PasswordHash: passwordHash,
		IsEnable:     uint8(res.IsEnable),
		Phone:        res.Phone,
		Email:        res.Email,
		IsAdmin:      uint8(res.IsAdmin),
		LoggedAt:     nil,
		CreatedAt:    nowTime,
		UpdatedAt:    nowTime,
	}

	user, err := api.userCase.CreateUser(c, &modelUser)
	if err != nil {
		logger.Warnf("Error creating user: %v", err)
		errRsp := ErrorResponse{
			Error:            RepositoryError,
			ErrorDescription: err.Error(),
		}
		c.JSON(500, errRsp)
		return
	}

	rsp := parseUserModel(*user)
	c.JSON(200, rsp)

}
