/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

import (
	"github.com/gin-gonic/gin"
	"github.com/sis-shen/sup-iam/internal/iam-api-server/v1/service"
)

type AuditAPI struct {
	auditCase service.AuditCaseInterface
}

func NewAuditAPI(auditCase service.AuditCaseInterface) *AuditAPI {
	return &AuditAPI{
		auditCase: auditCase,
	}
}

// Get /api/v1/audits/bindings
// 获取 Binding Audit 列表
func (api *AuditAPI) ApiV1AuditsBindingsGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/v1/audits/bindings/:id
// 获取 Binding Audit
func (api *AuditAPI) ApiV1AuditsBindingsIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/v1/audits/policies
// 获取 Policy Audit 列表
func (api *AuditAPI) ApiV1AuditsPoliciesGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /api/v1/audits/policies/:id
// 获取 Policy Audit
func (api *AuditAPI) ApiV1AuditsPoliciesIdGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
