/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

import (
	"time"
)

type GetPolicyAuditResponse struct {
	PolicyAuditId int64 `json:"policy_audit_id,omitempty"`

	Name string `json:"name,omitempty"`

	Username string `json:"username,omitempty"`

	Description *string `json:"description,omitempty"`

	// 策略内容快照
	PolicyShadow *string `json:"policy_shadow,omitempty"`

	ExtendShadow *string `json:"extend_shadow,omitempty"`

	CreateTime time.Time `json:"create_time,omitempty"`

	// 操作内容
	ActionContent string `json:"action_content,omitempty"`
}
