/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

// ChangePasswordRequest - 修改密码请求
type ChangePasswordRequest struct {

	// 旧密码
	OldPassword string `json:"old_password"`

	// 新密码
	NewPassword string `json:"new_password"`
}
