/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

import (
	"time"
)

// MeResponse - 当前用户信息
type MeResponse struct {

	// 用户ID
	Id int64 `json:"id,omitempty"`

	// 用户名
	Username string `json:"username,omitempty"`

	// 显示名称
	Nickname string `json:"nickname,omitempty"`

	// 邮箱
	Email *string `json:"email,omitempty"`

	// 手机号
	Phone *string `json:"phone,omitempty"`

	// 管理员标识
	IsAdmin int32 `json:"is_admin,omitempty"`

	// 用户状态
	IsEnable int32 `json:"is_enable,omitempty"`

	// 用户角色
	Role string `json:"role,omitempty"`

	// 最后登录时间
	LoggedAt *time.Time `json:"logged_at,omitempty"`
}
