/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

import (
	"time"
)

type GetBindingAuditResponse struct {
	BindingAuditId int64 `json:"binding_audit_id,omitempty"`

	SecretId int64 `json:"secret_id,omitempty"`

	PolicyId int64 `json:"policy_id,omitempty"`

	Username string `json:"username,omitempty"`

	CreateTime time.Time `json:"create_time,omitempty"`

	// 操作内容
	ActionContent string `json:"action_content,omitempty"`
}
