/*
 * IAM API Control Plane
 *
 * 身份与访问管理系统控制面API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package iamapiserver

type SecretPolicyListResponse struct {
	Items []PolicyResponse `json:"items,omitempty"`

	Page int32 `json:"page,omitempty"`

	PageSize int32 `json:"page_size,omitempty"`

	Total int64 `json:"total,omitempty"`

	SecretId int64 `json:"secret_id,omitempty"`
}
