// pump is iam analytics purger that moves the data generated by your iam-auth-server nodes to any back-end.
// It is primarily used to display your analytics data in the iam operating system.
package main

import "github.com/sis-shen/sup-iam/internal/iam-pump"

func main() {
	app := iampump.NewApp("iam-pump")
	if err := app.Start(); err != nil {
		panic(err)
	}
}
