/*
* IAM API Control Plane
*
* 身份与访问管理系统控制面API
*
* API version: 1.0.0
* Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"context"
	"fmt"
	"github.com/sis-shen/sup-iam/internal/iam-api-server/v1/cache"
	"github.com/sis-shen/sup-iam/internal/iam-api-server/v1/config"
	server "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/iamapiserver"
	storeredis "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/redis"
	mysqlDB "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/repository/mysql"
	"github.com/sis-shen/sup-iam/internal/iam-api-server/v1/rpc"
	"github.com/sis-shen/sup-iam/internal/iam-api-server/v1/service"
	"github.com/sis-shen/sup-iam/internal/pkg/jwt"
	"github.com/sis-shen/sup-iam/internal/pkg/log"
	"github.com/sis-shen/sup-iam/internal/pkg/middleware"
	"github.com/sis-shen/sup-iam/internal/pkg/proto/rpc/v2"
	genericapiserver "github.com/sis-shen/sup-iam/internal/pkg/server"
	"github.com/spf13/pflag"
	etcdclient "go.etcd.io/etcd/client/v3"
	"go.etcd.io/etcd/client/v3/naming/endpoints"
	"golang.org/x/sync/errgroup"
	"google.golang.org/grpc"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	mysqllogger "gorm.io/gorm/logger"
	"net"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"
)

var (
	Version    string
	BuildTime  string
	CommitHash string
)

// 定义一个结构体，用于存放需要优雅关闭的资源
type shutdownResources struct {
	httpServer    *http.Server
	grpcServer    *grpc.Server
	etcdLeaseID   etcdclient.LeaseID
	etcdCli       *etcdclient.Client
	stopKeepAlive chan struct{}
	stopChan      chan struct{}
}

func main() {
	var showVersion bool
	pflag.BoolVarP(&showVersion, "version", "v", false, "show version")
	pflag.Parse()
	if showVersion {
		//显示版本信息后退出
		fmt.Printf("Version: %s\nBuildTime: %s\nCommitHash: %s\n", Version, BuildTime, CommitHash)
		return
	}
	shutdownRes := &shutdownResources{
		stopChan: make(chan struct{}),
	}

	//======== 1.加载配置
	conf, err := config.Load("")
	if err != nil {
		fmt.Printf("配置文件加载失败: %v", err.Error())
		return
	}

	errs := conf.Log.Validate()
	if errs != nil && len(errs) > 0 {
		fmt.Printf("fail to validate log: %v", errs)
		return
	}

	//====== 2. 加载组件
	logger := log.New(conf.Log)
	mysqlCli, err := initMySQLWithRetry(*conf.MySQL, logger)
	if err != nil {
		logger.Errorf("fail to init mysql: %v", err)
		return
	}
	redisCli, err := storeredis.Init(*conf.Redis)
	if err != nil {
		logger.Errorf("fail to init redis: %v", err)
		return
	}
	redisCli = redisCli.WithStopChan(shutdownRes.stopChan)

	if conf.Server.EnableRedisSink {
		var level log.Level
		if err := level.UnmarshalText([]byte(conf.Server.SinkLevel)); err != nil {
			level = log.InfoLevel
		}
		logger = log.WrapWithRedis(logger, redisCli.DB(),
			conf.Server.RedisLogKeyPrefix,
			level)
	}
	jm := initJWTManager(*conf.JWT)
	jwtMiddleWare := middleware.JWTAuthMiddleware(&jm, conf.JWT.SkipPaths)
	blackList := cache.NewRedisTokenBlackList(redisCli.DB(), conf.Server.BlackListTTL)

	// =======3. 创建errgroup管理
	g, ctx := errgroup.WithContext(context.Background())

	// ========= 4.初始化router
	routes := initRoutes(logger, mysqlCli, jm, blackList)
	router := server.NewRouter(routes, jwtMiddleWare)

	//======== 5.启动HTTPServer
	go genericapiserver.ServeHealthCheck(conf.Server.HealthPath, conf.Server.HealthAddr)
	address := fmt.Sprintf("%s:%d", conf.Server.Host, conf.Server.Port)
	httpServer := &http.Server{
		Addr:         address,
		Handler:      router,
		ReadTimeout:  conf.Server.ReadTimeout,
		WriteTimeout: conf.Server.WriteTimeout,
		IdleTimeout:  conf.Server.IdleTimeout,
	}

	g.Go(func() error {
		shutdownRes.httpServer = httpServer
		logger.Infof("starting http server on %s", address)
		if err := httpServer.ListenAndServe(); err != nil {
			return fmt.Errorf("fail to start http server: %v", err)
		}
		return nil
	})

	// ==== 6.启动gRPC
	grpcLis, err := net.Listen("tcp", fmt.Sprintf("%s:%d", conf.GrpcConfig.Host, conf.GrpcConfig.Port))
	if err != nil {
		logger.Errorf("grpc fail to list: %v", err)
	}
	grpcServer := initGrpcServer(mysqlCli)

	if conf.GrpcConfig.EtcdServerDiscovery {
		cli, err := etcdclient.NewFromURL(fmt.Sprintf("%s:%d", conf.GrpcConfig.EtcdHost, conf.GrpcConfig.EtcdPort))
		if err != nil {
			logger.Errorf("fail to create etcd client: %v", err)
			return
		}
		shutdownRes.etcdCli = cli

		id, err := registerToEtcdWithLease(*conf.GrpcConfig, cli, logger)
		if err != nil {
			logger.Errorf("fail to register to etcd: %v", err)
			return
		}
		shutdownRes.etcdLeaseID = *id

		stopChan := make(chan struct{})
		shutdownRes.stopKeepAlive = stopChan
		go keepAliveLease(cli, *id, stopChan, logger)
	}

	//启动grpc
	g.Go(func() error {
		logger.Infof("starting grpc server")
		shutdownRes.grpcServer = grpcServer
		if err := grpcServer.Serve(grpcLis); err != nil {
			return fmt.Errorf("fail to start grpc server: %v", err)
		}
		return nil
	})

	// ====== 7.监听系统退出信号
	g.Go(func() error {
		quit := make(chan os.Signal, 1)
		signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
		select {
		case sig := <-quit:
			logger.Infof("receive signal: %v, start to graceful shutdown", sig)
		case <-ctx.Done():
			logger.Infof("unknown error in goroutine")
		}

		//关停server
		shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), conf.Server.GraceTimeout)
		defer shutdownCancel()

		if err := shutdownRes.httpServer.Shutdown(shutdownCtx); err != nil {
			logger.Errorf("fail to shutdown http server: %v", err)
		}

		//关停grpc
		shutdownRes.grpcServer.GracefulStop()

		//关停etcd
		if conf.GrpcConfig.EtcdServerDiscovery && shutdownRes.etcdCli != nil {
			if shutdownRes.stopKeepAlive != nil {
				close(shutdownRes.stopKeepAlive)
			}
			// 撤销租约
			if shutdownRes.etcdLeaseID != 0 {
				_, err := shutdownRes.etcdCli.Revoke(context.Background(), shutdownRes.etcdLeaseID)
				if err != nil {
					logger.Errorf("fail to revoke etcd lease: %v", err)
				} else {
					logger.Infof("revoked etcd lease: %v", shutdownRes.etcdLeaseID)
				}
			}
			//关闭etcd客户端链接
			if err := shutdownRes.etcdCli.Close(); err != nil {
				logger.Errorf("fail to close etcd: %v", err)
			}
		}

		return nil
	})

	// 8.等待所有goroutine结束
	if err := g.Wait(); err != nil {
		logger.Fatalf("fail to wait: %v", err)
	}

	// 9. 关闭数据库连接
	if sqlDB, err := mysqlCli.DB(); err != nil && sqlDB != nil {
		err := sqlDB.Close()
		if err != nil {
			logger.Errorf("close mysql db in exception: %v", err)
		}
	}

	if shutdownRes.stopChan != nil {
		close(shutdownRes.stopChan)
	}
	err = redisCli.DB().Close()
	if err != nil {
		logger.Errorf("close redis client in exception: %v", err)
	}

	logger.Infof("finish graceful shutdown")
}

func registerToEtcdWithLease(conf config.GrpcConfig, etcdCli *etcdclient.Client, logger log.Logger) (*etcdclient.LeaseID, error) {
	// 创建 endpoints 管理器
	em, err := endpoints.NewManager(etcdCli, conf.ServiceName)
	if err != nil {
		return nil, err
	}

	// 创建租约
	ttl := int64(conf.LeaseTTL.Seconds())
	if ttl == 0 {
		ttl = 10
	}
	lease, err := etcdCli.Grant(context.Background(), ttl)
	if err != nil {
		return nil, err
	}

	// 注册当前实例的地址，使用唯一 key（比如加上 hostname 或 IP）
	// 注意：每个实例应该有唯一的 key，否则会互相覆盖
	key := fmt.Sprintf("%s/%s", conf.ServiceName, conf.ServiceAddress)
	err = em.AddEndpoint(context.Background(), key, endpoints.Endpoint{
		Addr: conf.ServiceAddress,
	}, etcdclient.WithLease(lease.ID))

	if err != nil {
		logger.Fatalf("fail to register to etcd: %v", err)
		return nil, err
	}

	logger.Infof("Service registered to etcd: %s -> %s (leaseID: %d, TTL: %ds)\n",
		key, conf.ServiceAddress, lease.ID, ttl)

	return &lease.ID, nil

}

// 续约函数：保持租约活跃
func keepAliveLease(cli *etcdclient.Client, leaseID etcdclient.LeaseID, stopCh <-chan struct{}, logger log.Logger) {
	// 注意：必须消费 KeepAlive 返回的 channel，否则租约不会自动续期
	keepAliveChan, err := cli.KeepAlive(context.Background(), leaseID)
	if err != nil {
		logger.Errorf("failed to start keepalive: %v", err)
		return
	}

	logger.Infof("etcd keepalive started for lease %d", leaseID)

	for {
		select {
		case <-stopCh:
			logger.Infof("stop keepalive for lease %d", leaseID)
			return
		case kaResp, ok := <-keepAliveChan:
			if !ok {
				// 通道关闭，说明连接异常
				logger.Warnf("etcd keepalive channel closed for lease %d", leaseID)
				return
			}
			if kaResp == nil {
				logger.Warnf("etcd keepalive response is nil, lease %d may have expired", leaseID)
				return
			}
			// 可选：记录续约成功（生产环境可设为 Debug 级别）
			logger.Debugf("etcd lease %d renewed, TTL: %d", kaResp.ID, kaResp.TTL)
		}
	}
}

func initGrpcServer(mysqlCli *gorm.DB) *grpc.Server {
	if mysqlCli == nil {
		return nil
	}

	grpcServer := grpc.NewServer()
	secretStore := mysqlDB.NewSecretStore(mysqlCli)
	secretCase := service.NewSecretCase(secretStore)

	handler := rpc.NewAuthQueryHandler(secretCase)
	pbv2.RegisterAuthQueryServiceServer(grpcServer, handler)

	return grpcServer
}

func initRoutes(logger log.Logger, mysqlCli *gorm.DB, jm jwt.Manager, blackList cache.TokenBlackListInterface) server.ApiHandleFunctions {
	userStore := mysqlDB.NewUserStore(mysqlCli)
	policyStore := mysqlDB.NewPolicyStore(mysqlCli)
	secretStore := mysqlDB.NewSecretStore(mysqlCli)
	bindingStore := mysqlDB.NewBindingStore(mysqlCli)
	AuditStore := mysqlDB.NewAuditStore(mysqlCli)

	hasher := service.NewInnerBcryptPasswordHasher(0)

	userCase := service.NewUserCase(userStore, hasher)
	policyCase := service.NewPolicyCase(policyStore)
	secretCase := service.NewSecretCase(secretStore)
	authCase := service.NewAuthCase(userStore, hasher, jm, blackList)
	bindingCase := service.NewBindingCase(bindingStore)
	auditCase := service.NewAuditCase(AuditStore)

	authAPI := server.NewAuthAPI(logger, jm, authCase, userCase)
	userAPI := server.NewUserAPI(userCase, logger)
	secretAPI := server.NewSecretAPI(secretCase, logger)
	policyAPI := server.NewPolicyAPI(policyCase, logger)
	bindingAPI := server.NewBindingAPI(bindingCase, logger)
	auditAPI := server.NewAuditAPI(auditCase)

	return server.ApiHandleFunctions{
		AuthAPI:    *authAPI,
		UserAPI:    *userAPI,
		SecretAPI:  *secretAPI,
		PolicyAPI:  *policyAPI,
		BindingAPI: *bindingAPI,
		AuditAPI:   *auditAPI,
	}
}

func initJWTManager(conf config.JWTConfig) jwt.Manager {
	con := jwt.Config{
		UserIDKey:         conf.UserIDKey,
		SecretKey:         conf.SecretKey,
		RefreshExpireTime: conf.RefreshTokenExpireTime,
		TokenExpireTime:   conf.AccessTokenExpireTime,
		Issuer:            conf.Issuer,
		TokenLookup:       conf.TokenLookup,
	}
	return *jwt.NewManager(&con)
}

func initMySQL(conf config.MySQLConfig, _ log.Logger) (*gorm.DB, error) {
	// 构建 DSN (Data Source Name)
	dsn := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?charset=utf8mb4&parseTime=True&loc=Local",
		conf.Username,
		conf.Password,
		conf.Host,
		conf.Port,
		conf.DatabaseName,
	)

	// 配置 GORM
	gormConfig := &gorm.Config{
		// 禁用默认事务（提高性能）
		SkipDefaultTransaction: true,
		// 命名策略
		NamingStrategy: nil,
		// 日志配置（使用项目中的 logger）
		Logger: mysqllogger.Default.LogMode(mysqllogger.Info),
	}

	// 打开数据库连接
	db, err := gorm.Open(mysql.Open(dsn), gormConfig)
	if err != nil {
		return nil, fmt.Errorf("failed to connect to mysql: %w", err)
	}

	// 获取底层的 sql.DB 对象进行连接池配置
	sqlDB, err := db.DB()
	if err != nil {
		return nil, fmt.Errorf("failed to get sql.DB: %w", err)
	}

	// 配置连接池
	sqlDB.SetMaxIdleConns(conf.MaxIdleConns)       // 最大空闲连接数
	sqlDB.SetMaxOpenConns(conf.MaxOpenConns)       // 最大打开连接数
	sqlDB.SetConnMaxLifetime(conf.ConnMaxLifetime) // 连接最大生命周期
	sqlDB.SetConnMaxIdleTime(conf.ConnMaxIdleTime)

	// 测试连接
	if err := sqlDB.Ping(); err != nil {
		return nil, fmt.Errorf("failed to ping mysql: %w", err)
	}

	return db, nil
}

func initMySQLWithRetry(conf config.MySQLConfig, logger log.Logger) (*gorm.DB, error) {
	var db *gorm.DB
	var err error

	maxRetries := conf.MaxRetries

	for i := 0; i < maxRetries; i++ {
		db, err = initMySQL(conf, logger)
		if err == nil {
			break
		}

		logger.Errorf("Failed to connect to MySQL (attempt %d/%d): %v\n", i+1, maxRetries, err)
		time.Sleep(5 * time.Second)
	}

	if err != nil {
		return nil, fmt.Errorf("failed to connect to MySQL after %d attempts: %w", maxRetries, err)
	}

	return db, nil
}
