// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sis-shen/sup-iam/internal/iam-api-server/v1/repository (interfaces: AuditRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mock/audit_repo_mock.go -package=mock . AuditRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/model"
	repository "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditRepository is a mock of AuditRepository interface.
type MockAuditRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditRepositoryMockRecorder is the mock recorder for MockAuditRepository.
type MockAuditRepositoryMockRecorder struct {
	mock *MockAuditRepository
}

// NewMockAuditRepository creates a new mock instance.
func NewMockAuditRepository(ctrl *gomock.Controller) *MockAuditRepository {
	mock := &MockAuditRepository{ctrl: ctrl}
	mock.recorder = &MockAuditRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditRepository) EXPECT() *MockAuditRepositoryMockRecorder {
	return m.recorder
}

// GetBindingAuditByID mocks base method.
func (m *MockAuditRepository) GetBindingAuditByID(ctx context.Context, id string) (*model.BindingAudit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBindingAuditByID", ctx, id)
	ret0, _ := ret[0].(*model.BindingAudit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBindingAuditByID indicates an expected call of GetBindingAuditByID.
func (mr *MockAuditRepositoryMockRecorder) GetBindingAuditByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBindingAuditByID", reflect.TypeOf((*MockAuditRepository)(nil).GetBindingAuditByID), ctx, id)
}

// GetBindingAuditList mocks base method.
func (m *MockAuditRepository) GetBindingAuditList(ctx context.Context, query repository.PageQuery) (repository.PageResult[*model.BindingAudit], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBindingAuditList", ctx, query)
	ret0, _ := ret[0].(repository.PageResult[*model.BindingAudit])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBindingAuditList indicates an expected call of GetBindingAuditList.
func (mr *MockAuditRepositoryMockRecorder) GetBindingAuditList(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBindingAuditList", reflect.TypeOf((*MockAuditRepository)(nil).GetBindingAuditList), ctx, query)
}

// GetPolicyAuditByID mocks base method.
func (m *MockAuditRepository) GetPolicyAuditByID(ctx context.Context, id string) (*model.PolicyAudit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicyAuditByID", ctx, id)
	ret0, _ := ret[0].(*model.PolicyAudit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicyAuditByID indicates an expected call of GetPolicyAuditByID.
func (mr *MockAuditRepositoryMockRecorder) GetPolicyAuditByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicyAuditByID", reflect.TypeOf((*MockAuditRepository)(nil).GetPolicyAuditByID), ctx, id)
}

// GetPolicyAuditList mocks base method.
func (m *MockAuditRepository) GetPolicyAuditList(ctx context.Context, query repository.PageQuery) (repository.PageResult[*model.PolicyAudit], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicyAuditList", ctx, query)
	ret0, _ := ret[0].(repository.PageResult[*model.PolicyAudit])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicyAuditList indicates an expected call of GetPolicyAuditList.
func (mr *MockAuditRepositoryMockRecorder) GetPolicyAuditList(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicyAuditList", reflect.TypeOf((*MockAuditRepository)(nil).GetPolicyAuditList), ctx, query)
}
