// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sis-shen/sup-iam/internal/iam-api-server/v1/repository (interfaces: BindingRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mock/binding_repo_mock.go -package=mock . BindingRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/model"
	repository "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockBindingRepository is a mock of BindingRepository interface.
type MockBindingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBindingRepositoryMockRecorder
	isgomock struct{}
}

// MockBindingRepositoryMockRecorder is the mock recorder for MockBindingRepository.
type MockBindingRepositoryMockRecorder struct {
	mock *MockBindingRepository
}

// NewMockBindingRepository creates a new mock instance.
func NewMockBindingRepository(ctrl *gomock.Controller) *MockBindingRepository {
	mock := &MockBindingRepository{ctrl: ctrl}
	mock.recorder = &MockBindingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBindingRepository) EXPECT() *MockBindingRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBindingRepository) Create(ctx context.Context, binding *model.Binding) (*model.Binding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, binding)
	ret0, _ := ret[0].(*model.Binding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBindingRepositoryMockRecorder) Create(ctx, binding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBindingRepository)(nil).Create), ctx, binding)
}

// DeleteByID mocks base method.
func (m *MockBindingRepository) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockBindingRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockBindingRepository)(nil).DeleteByID), ctx, id)
}

// GetByID mocks base method.
func (m *MockBindingRepository) GetByID(ctx context.Context, id string) (*model.Binding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Binding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBindingRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBindingRepository)(nil).GetByID), ctx, id)
}

// GetListByUserID mocks base method.
func (m *MockBindingRepository) GetListByUserID(ctx context.Context, id string, query repository.PageQuery) (repository.PageResult[*model.Binding], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListByUserID", ctx, id, query)
	ret0, _ := ret[0].(repository.PageResult[*model.Binding])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListByUserID indicates an expected call of GetListByUserID.
func (mr *MockBindingRepositoryMockRecorder) GetListByUserID(ctx, id, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListByUserID", reflect.TypeOf((*MockBindingRepository)(nil).GetListByUserID), ctx, id, query)
}
