// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sis-shen/sup-iam/internal/iam-api-server/v1/repository (interfaces: PolicyRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mock/policy_repo_mock.go -package=mock . PolicyRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/model"
	repository "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockPolicyRepository is a mock of PolicyRepository interface.
type MockPolicyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyRepositoryMockRecorder
	isgomock struct{}
}

// MockPolicyRepositoryMockRecorder is the mock recorder for MockPolicyRepository.
type MockPolicyRepositoryMockRecorder struct {
	mock *MockPolicyRepository
}

// NewMockPolicyRepository creates a new mock instance.
func NewMockPolicyRepository(ctrl *gomock.Controller) *MockPolicyRepository {
	mock := &MockPolicyRepository{ctrl: ctrl}
	mock.recorder = &MockPolicyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyRepository) EXPECT() *MockPolicyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPolicyRepository) Create(ctx context.Context, policy *model.Policy) (*model.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, policy)
	ret0, _ := ret[0].(*model.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPolicyRepositoryMockRecorder) Create(ctx, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPolicyRepository)(nil).Create), ctx, policy)
}

// DeleteByID mocks base method.
func (m *MockPolicyRepository) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockPolicyRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockPolicyRepository)(nil).DeleteByID), ctx, id)
}

// GetByID mocks base method.
func (m *MockPolicyRepository) GetByID(ctx context.Context, id string) (*model.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPolicyRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPolicyRepository)(nil).GetByID), ctx, id)
}

// GetListByUserID mocks base method.
func (m *MockPolicyRepository) GetListByUserID(ctx context.Context, id string, query repository.PageQuery) (repository.PageResult[*model.Policy], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListByUserID", ctx, id, query)
	ret0, _ := ret[0].(repository.PageResult[*model.Policy])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListByUserID indicates an expected call of GetListByUserID.
func (mr *MockPolicyRepositoryMockRecorder) GetListByUserID(ctx, id, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListByUserID", reflect.TypeOf((*MockPolicyRepository)(nil).GetListByUserID), ctx, id, query)
}

// GetSecretListByPolicyID mocks base method.
func (m *MockPolicyRepository) GetSecretListByPolicyID(ctx context.Context, id string, query repository.PageQuery) (repository.PageResult[*model.Secret], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretListByPolicyID", ctx, id, query)
	ret0, _ := ret[0].(repository.PageResult[*model.Secret])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretListByPolicyID indicates an expected call of GetSecretListByPolicyID.
func (mr *MockPolicyRepositoryMockRecorder) GetSecretListByPolicyID(ctx, id, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretListByPolicyID", reflect.TypeOf((*MockPolicyRepository)(nil).GetSecretListByPolicyID), ctx, id, query)
}

// Update mocks base method.
func (m *MockPolicyRepository) Update(ctx context.Context, policy *model.Policy) (*model.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, policy)
	ret0, _ := ret[0].(*model.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPolicyRepositoryMockRecorder) Update(ctx, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPolicyRepository)(nil).Update), ctx, policy)
}
