// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sis-shen/sup-iam/internal/iam-api-server/v1/repository (interfaces: SecretRepository)
//
// Generated by this command:
//
//	mockgen -destination=./mock/secret_repo_mock.go -package=mock . SecretRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/model"
	repository "github.com/sis-shen/sup-iam/internal/iam-api-server/v1/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretRepository is a mock of SecretRepository interface.
type MockSecretRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSecretRepositoryMockRecorder
	isgomock struct{}
}

// MockSecretRepositoryMockRecorder is the mock recorder for MockSecretRepository.
type MockSecretRepositoryMockRecorder struct {
	mock *MockSecretRepository
}

// NewMockSecretRepository creates a new mock instance.
func NewMockSecretRepository(ctrl *gomock.Controller) *MockSecretRepository {
	mock := &MockSecretRepository{ctrl: ctrl}
	mock.recorder = &MockSecretRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretRepository) EXPECT() *MockSecretRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSecretRepository) Create(ctx context.Context, secret *model.Secret) (*model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, secret)
	ret0, _ := ret[0].(*model.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSecretRepositoryMockRecorder) Create(ctx, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSecretRepository)(nil).Create), ctx, secret)
}

// DeleteByID mocks base method.
func (m *MockSecretRepository) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockSecretRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockSecretRepository)(nil).DeleteByID), ctx, id)
}

// GetAllPoliciesMap mocks base method.
func (m *MockSecretRepository) GetAllPoliciesMap(ctx context.Context) (map[string][]*model.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPoliciesMap", ctx)
	ret0, _ := ret[0].(map[string][]*model.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPoliciesMap indicates an expected call of GetAllPoliciesMap.
func (mr *MockSecretRepositoryMockRecorder) GetAllPoliciesMap(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPoliciesMap", reflect.TypeOf((*MockSecretRepository)(nil).GetAllPoliciesMap), ctx)
}

// GetAllSecrets mocks base method.
func (m *MockSecretRepository) GetAllSecrets(ctx context.Context) ([]*model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSecrets", ctx)
	ret0, _ := ret[0].([]*model.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSecrets indicates an expected call of GetAllSecrets.
func (mr *MockSecretRepositoryMockRecorder) GetAllSecrets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSecrets", reflect.TypeOf((*MockSecretRepository)(nil).GetAllSecrets), ctx)
}

// GetByAK mocks base method.
func (m *MockSecretRepository) GetByAK(ctx context.Context, ak string) (*model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAK", ctx, ak)
	ret0, _ := ret[0].(*model.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAK indicates an expected call of GetByAK.
func (mr *MockSecretRepositoryMockRecorder) GetByAK(ctx, ak any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAK", reflect.TypeOf((*MockSecretRepository)(nil).GetByAK), ctx, ak)
}

// GetByID mocks base method.
func (m *MockSecretRepository) GetByID(ctx context.Context, id string) (*model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSecretRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSecretRepository)(nil).GetByID), ctx, id)
}

// GetListByUserID mocks base method.
func (m *MockSecretRepository) GetListByUserID(ctx context.Context, id string, query repository.PageQuery) (repository.PageResult[*model.Secret], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListByUserID", ctx, id, query)
	ret0, _ := ret[0].(repository.PageResult[*model.Secret])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListByUserID indicates an expected call of GetListByUserID.
func (mr *MockSecretRepositoryMockRecorder) GetListByUserID(ctx, id, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListByUserID", reflect.TypeOf((*MockSecretRepository)(nil).GetListByUserID), ctx, id, query)
}

// GetPolicyListBySecretID mocks base method.
func (m *MockSecretRepository) GetPolicyListBySecretID(ctx context.Context, id string, query repository.PageQuery) (repository.PageResult[*model.Policy], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicyListBySecretID", ctx, id, query)
	ret0, _ := ret[0].(repository.PageResult[*model.Policy])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicyListBySecretID indicates an expected call of GetPolicyListBySecretID.
func (mr *MockSecretRepositoryMockRecorder) GetPolicyListBySecretID(ctx, id, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicyListBySecretID", reflect.TypeOf((*MockSecretRepository)(nil).GetPolicyListBySecretID), ctx, id, query)
}

// Update mocks base method.
func (m *MockSecretRepository) Update(ctx context.Context, secret *model.Secret) (*model.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, secret)
	ret0, _ := ret[0].(*model.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSecretRepositoryMockRecorder) Update(ctx, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSecretRepository)(nil).Update), ctx, secret)
}
