// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: auth_quey.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSecretByAKRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKey     string                 `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretByAKRequest) Reset() {
	*x = GetSecretByAKRequest{}
	mi := &file_auth_quey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretByAKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretByAKRequest) ProtoMessage() {}

func (x *GetSecretByAKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_quey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretByAKRequest.ProtoReflect.Descriptor instead.
func (*GetSecretByAKRequest) Descriptor() ([]byte, []int) {
	return file_auth_quey_proto_rawDescGZIP(), []int{0}
}

func (x *GetSecretByAKRequest) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

type GetSecretByAKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretByAKResponse) Reset() {
	*x = GetSecretByAKResponse{}
	mi := &file_auth_quey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretByAKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretByAKResponse) ProtoMessage() {}

func (x *GetSecretByAKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_quey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretByAKResponse.ProtoReflect.Descriptor instead.
func (*GetSecretByAKResponse) Descriptor() ([]byte, []int) {
	return file_auth_quey_proto_rawDescGZIP(), []int{1}
}

func (x *GetSecretByAKResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type GetPolicyBySecretIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyBySecretIDRequest) Reset() {
	*x = GetPolicyBySecretIDRequest{}
	mi := &file_auth_quey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyBySecretIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyBySecretIDRequest) ProtoMessage() {}

func (x *GetPolicyBySecretIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_quey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyBySecretIDRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyBySecretIDRequest) Descriptor() ([]byte, []int) {
	return file_auth_quey_proto_rawDescGZIP(), []int{2}
}

func (x *GetPolicyBySecretIDRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

type GetPolicyBySecretIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyList    []*Policy              `protobuf:"bytes,1,rep,name=policy_list,json=policyList,proto3" json:"policy_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyBySecretIDResponse) Reset() {
	*x = GetPolicyBySecretIDResponse{}
	mi := &file_auth_quey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyBySecretIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyBySecretIDResponse) ProtoMessage() {}

func (x *GetPolicyBySecretIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_quey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyBySecretIDResponse.ProtoReflect.Descriptor instead.
func (*GetPolicyBySecretIDResponse) Descriptor() ([]byte, []int) {
	return file_auth_quey_proto_rawDescGZIP(), []int{3}
}

func (x *GetPolicyBySecretIDResponse) GetPolicyList() []*Policy {
	if x != nil {
		return x.PolicyList
	}
	return nil
}

var File_auth_quey_proto protoreflect.FileDescriptor

const file_auth_quey_proto_rawDesc = "" +
	"\n" +
	"\x0fauth_quey.proto\x12\bproto.v1\x1a\vmodel.proto\"5\n" +
	"\x14GetSecretByAKRequest\x12\x1d\n" +
	"\n" +
	"access_key\x18\x01 \x01(\tR\taccessKey\"A\n" +
	"\x15GetSecretByAKResponse\x12(\n" +
	"\x06secret\x18\x01 \x01(\v2\x10.proto.v1.SecretR\x06secret\"9\n" +
	"\x1aGetPolicyBySecretIDRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\"P\n" +
	"\x1bGetPolicyBySecretIDResponse\x121\n" +
	"\vpolicy_list\x18\x01 \x03(\v2\x10.proto.v1.PolicyR\n" +
	"policyList2\xc8\x01\n" +
	"\x10AuthQueryService\x12P\n" +
	"\rGetSecretByAK\x12\x1e.proto.v1.GetSecretByAKRequest\x1a\x1f.proto.v1.GetSecretByAKResponse\x12b\n" +
	"\x13GetPolicyBySecretID\x12$.proto.v1.GetPolicyBySecretIDRequest\x1a%.proto.v1.GetPolicyBySecretIDResponseB8Z6github.com/sis-shen/sup-iam/internal/proto/tpc/v1;pbv1b\x06proto3"

var (
	file_auth_quey_proto_rawDescOnce sync.Once
	file_auth_quey_proto_rawDescData []byte
)

func file_auth_quey_proto_rawDescGZIP() []byte {
	file_auth_quey_proto_rawDescOnce.Do(func() {
		file_auth_quey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_quey_proto_rawDesc), len(file_auth_quey_proto_rawDesc)))
	})
	return file_auth_quey_proto_rawDescData
}

var file_auth_quey_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auth_quey_proto_goTypes = []any{
	(*GetSecretByAKRequest)(nil),        // 0: proto.v1.GetSecretByAKRequest
	(*GetSecretByAKResponse)(nil),       // 1: proto.v1.GetSecretByAKResponse
	(*GetPolicyBySecretIDRequest)(nil),  // 2: proto.v1.GetPolicyBySecretIDRequest
	(*GetPolicyBySecretIDResponse)(nil), // 3: proto.v1.GetPolicyBySecretIDResponse
	(*Secret)(nil),                      // 4: proto.v1.Secret
	(*Policy)(nil),                      // 5: proto.v1.Policy
}
var file_auth_quey_proto_depIdxs = []int32{
	4, // 0: proto.v1.GetSecretByAKResponse.secret:type_name -> proto.v1.Secret
	5, // 1: proto.v1.GetPolicyBySecretIDResponse.policy_list:type_name -> proto.v1.Policy
	0, // 2: proto.v1.AuthQueryService.GetSecretByAK:input_type -> proto.v1.GetSecretByAKRequest
	2, // 3: proto.v1.AuthQueryService.GetPolicyBySecretID:input_type -> proto.v1.GetPolicyBySecretIDRequest
	1, // 4: proto.v1.AuthQueryService.GetSecretByAK:output_type -> proto.v1.GetSecretByAKResponse
	3, // 5: proto.v1.AuthQueryService.GetPolicyBySecretID:output_type -> proto.v1.GetPolicyBySecretIDResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_quey_proto_init() }
func file_auth_quey_proto_init() {
	if File_auth_quey_proto != nil {
		return
	}
	file_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_quey_proto_rawDesc), len(file_auth_quey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_quey_proto_goTypes,
		DependencyIndexes: file_auth_quey_proto_depIdxs,
		MessageInfos:      file_auth_quey_proto_msgTypes,
	}.Build()
	File_auth_quey_proto = out.File
	file_auth_quey_proto_goTypes = nil
	file_auth_quey_proto_depIdxs = nil
}
