// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: auth_quey.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthQueryService_GetSecretByAK_FullMethodName       = "/proto.v1.AuthQueryService/GetSecretByAK"
	AuthQueryService_GetPolicyBySecretID_FullMethodName = "/proto.v1.AuthQueryService/GetPolicyBySecretID"
)

// AuthQueryServiceClient is the client API for AuthQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthQueryServiceClient interface {
	GetSecretByAK(ctx context.Context, in *GetSecretByAKRequest, opts ...grpc.CallOption) (*GetSecretByAKResponse, error)
	GetPolicyBySecretID(ctx context.Context, in *GetPolicyBySecretIDRequest, opts ...grpc.CallOption) (*GetPolicyBySecretIDResponse, error)
}

type authQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthQueryServiceClient(cc grpc.ClientConnInterface) AuthQueryServiceClient {
	return &authQueryServiceClient{cc}
}

func (c *authQueryServiceClient) GetSecretByAK(ctx context.Context, in *GetSecretByAKRequest, opts ...grpc.CallOption) (*GetSecretByAKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretByAKResponse)
	err := c.cc.Invoke(ctx, AuthQueryService_GetSecretByAK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authQueryServiceClient) GetPolicyBySecretID(ctx context.Context, in *GetPolicyBySecretIDRequest, opts ...grpc.CallOption) (*GetPolicyBySecretIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPolicyBySecretIDResponse)
	err := c.cc.Invoke(ctx, AuthQueryService_GetPolicyBySecretID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthQueryServiceServer is the server API for AuthQueryService service.
// All implementations must embed UnimplementedAuthQueryServiceServer
// for forward compatibility.
type AuthQueryServiceServer interface {
	GetSecretByAK(context.Context, *GetSecretByAKRequest) (*GetSecretByAKResponse, error)
	GetPolicyBySecretID(context.Context, *GetPolicyBySecretIDRequest) (*GetPolicyBySecretIDResponse, error)
	mustEmbedUnimplementedAuthQueryServiceServer()
}

// UnimplementedAuthQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthQueryServiceServer struct{}

func (UnimplementedAuthQueryServiceServer) GetSecretByAK(context.Context, *GetSecretByAKRequest) (*GetSecretByAKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecretByAK not implemented")
}
func (UnimplementedAuthQueryServiceServer) GetPolicyBySecretID(context.Context, *GetPolicyBySecretIDRequest) (*GetPolicyBySecretIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicyBySecretID not implemented")
}
func (UnimplementedAuthQueryServiceServer) mustEmbedUnimplementedAuthQueryServiceServer() {}
func (UnimplementedAuthQueryServiceServer) testEmbeddedByValue()                          {}

// UnsafeAuthQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthQueryServiceServer will
// result in compilation errors.
type UnsafeAuthQueryServiceServer interface {
	mustEmbedUnimplementedAuthQueryServiceServer()
}

func RegisterAuthQueryServiceServer(s grpc.ServiceRegistrar, srv AuthQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthQueryService_ServiceDesc, srv)
}

func _AuthQueryService_GetSecretByAK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretByAKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthQueryServiceServer).GetSecretByAK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthQueryService_GetSecretByAK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthQueryServiceServer).GetSecretByAK(ctx, req.(*GetSecretByAKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthQueryService_GetPolicyBySecretID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyBySecretIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthQueryServiceServer).GetPolicyBySecretID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthQueryService_GetPolicyBySecretID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthQueryServiceServer).GetPolicyBySecretID(ctx, req.(*GetPolicyBySecretIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthQueryService_ServiceDesc is the grpc.ServiceDesc for AuthQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.AuthQueryService",
	HandlerType: (*AuthQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSecretByAK",
			Handler:    _AuthQueryService_GetSecretByAK_Handler,
		},
		{
			MethodName: "GetPolicyBySecretID",
			Handler:    _AuthQueryService_GetPolicyBySecretID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_quey.proto",
}
